### ISSUE TITLE
Pages - functions routing

### ISSUE THREAD

**Issue by dagnelies** [cloudflare/cloudflare-docs#10014]
### Which Cloudflare product does this pertain to?

Pages

### Existing documentation URL(s)

https://github.com/cloudflare/cloudflare-docs/blob/production/content/pages/platform/functions/routing.md

### What changes are you suggesting?

In "workers", for really large or complex APIs, with dependencies and such, the codebase grows a lot because you package everything in a single "entry point". This has negative impact on worker size, starting time, memory usage and so as the API "grows".

I would like to know if functions suffers the same issue. Are all functions files packaged in a single "bundle" under the hood? Or is each function compiled on its own, with its own entrypoint, so that adding a single function with a larger dependency or complexity has no impact on the others?

**Comment by deadlypants1973** [comment]
Hi @dagnelies , Functions are Workers (refer to the blue aside on the top of the page: https://developers.cloudflare.com/workers/platform/pricing) so they will function the same as Workers.

Are all functions files packaged in a single "bundle" under the hood? -> yes
Or is each function compiled on its own, with its own entrypoint, so that adding a single function with a larger dependency or complexity has no impact on the others? -> no

Thank you.
