### ISSUE TITLE
Availability of video Stream service in China, contradicting pages.

### ISSUE THREAD

**Issue by hdotnet** [cloudflare/cloudflare-docs#10058]
### Which Cloudflare product does this pertain to?

Stream

### Existing documentation URL(s)

[https://developers.cloudflare.com/china-network/reference/available-products/](https://developers.cloudflare.com/china-network/reference/available-products/)

### What changes are you suggesting?

The developer documentation page suggests that the CF Stream service is not available in China.

However the Cloudflare Stream product page suggests that it is:

[https://www.cloudflare.com/en-gb/products/stream-delivery/](https://www.cloudflare.com/en-gb/products/stream-delivery/)

Which is correct?

### Additional information

<img width="1188" alt="Screenshot 2023-07-26 at 16 27 16" src="https://github.com/cloudflare/cloudflare-docs/assets/8127931/70e9a449-f402-4fd9-beca-18abd956b2ef">

**Comment by tsmith512** [comment]
Hey there! PM for Stream here. Stream and Stream Delivery are two different things. Stream _Delivery_ (https://www.cloudflare.com/en-gb/products/stream-delivery/) is essentially a paid tier of our CDN product. It depends on the origin preparing all the media assets, manifests, and encoded segments --- leveraging Cloudflare only as a CDN to cache them. That works on our China Network because China Network-enabled zones are covered by that CDN.

Cloudflare _Stream_ (https://www.cloudflare.com/en-gb/products/cloudflare-stream/) is a solution that allows customers to upload or live stream video. Stream will encode/transcode segments, generate manifests, and deliver for playback in multiple bitrates. Our encoding framework does not currently operate on the China Network so on-demand and live playback may see increased latency or freezing.

Thank you for raising this issue. I'll see what info I can gather to clarify https://developers.cloudflare.com/china-network/reference/available-products/

**Comment by 7oque** [comment]
Interesting - would it be possible to serve a HLS stream from cloudflares stream delivery service? We are interested in serving non-live-stream media over HLS to leverage the encoding features.

**Comment by tsmith512** [comment]
Yes, but with Stream _Delivery,_ you would need to handle creating the HLS manifest and encoded segments for all bitrates/resolutions you want to deliver. The Delivery service is CDN only.

_Stream_ does the HLS for you, and if the use-case is an on-demand (not live) video, then you just upload a video to Stream, which will offer HLS (or DASH) playback at a handful of resolutions/formats.

**Comment by hdotnet** [comment]
- encode and serve your own stuff via the [CDN does work in China](https://www.cloudflare.com/en-gb/products/stream-delivery/)
- The plug and play [admin on the dashboard] is available globally, but not China (https://www.cloudflare.com/en-gb/products/cloudflare-stream/).

You need an ICP to serve video in China, so the latter service might cause an issue in China on partner networks/infra.
