### ISSUE TITLE
Actual turnstile client-side verification code

### ISSUE THREAD

**Issue by afjoseph** [cloudflare/cloudflare-docs#10139]
### Which Cloudflare product(s) does this pertain to?

Turnstile

### Subject Matter

Turnstile

### Content Location

https://github.com/cloudflare/cloudflare-docs/tree/9241d55701b1ccfdf0387ff4bea9f7e240a85add/content/turnstile

### Additional information

Hey guys. Is the turnstile code hosted [on challenges.cloudflare.com](https://challenges.cloudflare.com/turnstile/v0/api.js) publicly available for auditing or is it closed-source? I see it's minified and might be readable but it would be nice to get the full thing (with comments and all).

Additionally, will the siteverify API code ever be publicly available? Just mentioning that you're doing "proof-of-work" and "proof-of-space" does, IMHO, merit some technical white paper or something detailed regarding the process of verification and attestation (or maybe I was blind and haven't seen the docs for that).

Cheers and many thanks. Hope this product kicks off

**Comment by migueldemoura** [comment]
Hi @afjoseph, I'm afraid we don't publish the original source code for the assets served under https://challenges.cloudflare.com/. The same applies to code that isn't sent to your browser, like the siteverify API. The API.js code should be readable (it's only minified), but if you need to resort to that, we have work to do to improve documentation.

Due to the nature of bot detection, we also don't go into specifics of how the challenges work besides what's already documented at https://developers.cloudflare.com/turnstile/ (which I assume you read):

> Those challenges include, proof-of-work, proof-of-space, probing for web APIs, and various other challenges for detecting browser-quirks and human behavior.

That said, if there's anything unclear about how to integrate Turnstile with your website or app, please do let us know!

**Comment by patriciasantaana** [comment]
Hi @afjoseph ! Since the issue has been addressed by the team, I will close it now. Feel free to open up a new issue or ask any questions.
