### ISSUE TITLE
wrangler install documentation is wrong

### ISSUE THREAD

**Issue by k-nearest-neighbor** [cloudflare/cloudflare-docs#11315]
### Example URL(s)

https://developers.cloudflare.com/workers/wrangler/install-and-update/

The install step does not work. It should be:

```
sudo npm install -g wrangler
```

### Actual Behavior

```
$ npm install wrangler --save-dev
...
$ which wrangler
... wrangler not found
```

### Expected Behavior

```
$ sudo npm install -g wrangler
...
$ which wrangler
/path/to/your/wrangler
```

**Comment by penalosa** [comment]
We've changed the installation documentation to encourage installing Wrangler locally into a project rather than globally on your computer. This has a number of benefits, including the ability to use different Wrangler versions in different projects, being able to ensure that you're using the same Wrangler version as the rest of your team in a project, and being able to have confidence that your CI system will be using the same version of Wrangler as you do locally.

To install Wrangler locally, you should run:

```sh
npm install wrangler --save-dev
```

in your project, after which you'll be able to run Wrangler subcommands by prefixing the command with `npx`, e.g.

```
npx wrangler --version
```
