### ISSUE TITLE
登陆cloudflare需要邮箱接收验证码，但是我邮箱没有收到邮件

### ISSUE THREAD

**Issue by doudou7554366** [cloudflare/cloudflare-docs#11625]
### Which Cloudflare product(s) does this pertain to?

Security Center

### Subject Matter

登陆cloudflare需要邮箱接收验证码，但是我邮箱没有收到邮件

### Content Location

登陆cloudflare需要邮箱接收验证码，但是我邮箱没有收到邮件，并且垃圾邮箱也没有找到

**Comment by kodster28** [comment]
Howdy @doudou7554366, from your description, it's not totally clear what your issue is.... but you might find some help in our [current documentation](https://developers.cloudflare.com/fundamentals/setup/account-setup/verify-email-address/) on the subject?

If not, you can try reaching out to [Cloudflare Support](https://developers.cloudflare.com/support/troubleshooting/general-troubleshooting/contacting-cloudflare-support/).
