### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by CAF-ID** [cloudflare/cloudflare-docs#11693]
### Example URL(s)

My vps died after running the command "warp-cli connect"
i using linux desktop client version

### Actual Behavior

My vps died after running the command "warp-cli connect"
i using linux desktop client version

### Expected Behavior

My vps died after running the command "warp-cli connect"
i using linux desktop client version

### Additional information

My vps died after running the command "warp-cli connect"
i using linux desktop client version

**Comment by kodster28** [comment]
Howdy @CAF-ID, you might try [`sudo warp-diag` or `sudo warp-diag feedback`](https://developers.cloudflare.com/warp-client/get-started/linux/#feedback) to identify the root cause of your issue.

If that doesn't work, this sounds like more of a bug than a documentation issue, so I'd recommend you reach out to [Cloudflare Support](/support/troubleshooting/general-troubleshooting/contacting-cloudflare-support/).
