### ISSUE TITLE
error:520

### ISSUE THREAD

**Issue by jnsirman** [cloudflare/cloudflare-docs#11831]
### Example URL(s)

https://russia.bschealthy.com

### Actual Behavior

When parsed to IP: 103.143.248.51, a 520 error occurs. How to solve it?
![6EM85C~X 3AY4)%5Y{IDLBE](https://github.com/cloudflare/cloudflare-docs/assets/150982113/d4f96501-2bc8-453b-a8f7-544cbf91731e)

### Expected Behavior

Can open the website normally

### Additional information

![image](https://github.com/cloudflare/cloudflare-docs/assets/150982113/66202886-1658-45c9-90b3-ea05744f05fa)

**Comment by jnsirman** [comment]
Hello, at first I thought it was because of the IP, so I changed the IP: 156.232.11.50, but it failed again, and I asked for a solution. Thank you.

**Comment by pedrosousa** [comment]
Hello @jnsirman 
This seems to be an issue with the origin server (behind Cloudflare). Almost all the requests in the logs you showed above were answered with an HTTP `444` status code, specific to the NGINX web server:

> A 444 status code is thrown when a website unexpectedly closes the connection without sending any response to the client. It is an unofficial code and specific to NGINX. There are multiple reasons why NGINX might throw this error.

You may want to check the configuration and the behavior of the origin server, since Cloudflare is able to reach the server but is not obtaining a proper response (like responses with an HTTP `200` status code).

For additional help, you should reach out to the [Cloudflare Community](https://community.cloudflare.com/), since we only handle documentation updates in this repository.
