### ISSUE TITLE
Update turnstile FAQ and other pages to clarify how to use turnstile on sites that are proxied by Cloudflare

### ISSUE THREAD

**Issue by MaximilianKohler** [cloudflare/cloudflare-docs#12102]
### Which Cloudflare product does this pertain to?

Turnstile

### Existing documentation URL(s)

* https://developers.cloudflare.com/turnstile/migration/
* https://developers.cloudflare.com/turnstile/frequently-asked-questions/

### What changes are you suggesting?

I am using Cloudflare DNS/nameservers to proxy a few domains for DDoS protection. I recently set up an email server (listmonk.app) on a subdomain and enabled the cloudflare proxy to protect my IP from DDoS attacks. 

My concern is that when people click the "unsubscribe" links they will be presented with a captcha puzzle and will close the tab and click "spam" instead. You can lower your security level to “Essentially off”, but that's not a good fix because it does it for the entire domain instead of just the subdomain that listmonk is installed on. I know that [Cloudflare uses hcaptcha by default](https://blog.cloudflare.com/moving-from-recaptcha-to-hcaptcha/). I learned about turnstile and it seems to be the solution for this. But there is no simple checkbox in https://dash.cloudflare.com/ to switch a website or subdomain to turnstile instead of hcaptcha. 

So I landed on the "migration from hcaptcha" page https://developers.cloudflare.com/turnstile/migration/migrating-from-hcaptcha/ since that seems to be the only option. Besides "inserting the Turnstile script snippet in your HTML’s `<head>` element", I have no clue what the rest of the instructions are telling me to do. Note that I have done nothing to set up hcaptcha. As far as I know, hcaptcha is built in and automatically enabled when you proxy a domain/subdomain with cloudflare.

After clicking on the recaptcha tab https://developers.cloudflare.com/turnstile/migration/migrating-from-recaptcha/ my understanding of these "migration" directions changed, and it now seems that they do not apply to my situation at all, and are rather for people who have explicitly set up these captchas on their website?

Can you please clarify the docs for people in my situation? One specific request would be to mention whether or not the default hcaptcha gets automatically disabled if someone in my case enables turnstile on their website. Or would that just run turnstile on top of hcaptcha? 

There really should be an option in the https://dash.cloudflare.com/ to "use turnstile instead of hcaptcha", but I don't see any place to send feedback for that.

**Comment by kodster28** [comment]
Howdy @MaximilianKohler, thanks for raising this issue. TL;DR, by using Cloudflare, you're getting Turnstile behavior on proxied hostnames by default.

I'll raise this to the team to help make that clearer in the documentation.

## More details

The blog you're referring to is a bit dated (2020). We've since switched the default Cloudflare behavior to be Managed challenges ([blog](https://blog.cloudflare.com/end-cloudflare-captcha/) | [docs](https://developers.cloudflare.com/waf/reference/cloudflare-challenges/#managed-challenge-recommended)).

All proxied hostnames use these Managed Challenges instead of CAPTCHAs. Managed challenges are designed to reduce the friction associated with hcaptcha or recaptcha and primarily use non-interactive challenges.

Turnstile also uses Managed Challenges. One of the main points of Turnstile as a product is to open this behavior up to folks who aren't using the CF proxy.

All that said, if you were worried about challenges triggering more often on a certain subdomain, you could:
1. Monitor your security events to see whether those challenges were issued.
2. Use a [Configuration Rule](https://developers.cloudflare.com/rules/configuration-rules/) to adjust your Security settings specifically for your email subdomain.

**Comment by kodster28** [comment]
Let me know if that solved your question or issue. If I don't hear anything in a few days, I'll close this out.

**Comment by MaximilianKohler** [comment]
Yes, thank you very much! That answered my questions and concerns very well. I would suggest adding that information to these pages:
* https://www.cloudflare.com/products/turnstile/
* https://dash.cloudflare.com/sign-up?to=/:account/turnstile
* and various pages in the docs https://developers.cloudflare.com/turnstile/

This issue should only be closed after that, no?

**Comment by kodster28** [comment]
As a team / repo, we'll consider this closed when it's updated in various places throughout our docs.

Can file internal tickets on the other ones.... but those are outside the scope of our team's work, so would just consider this issue "addressed" once we link a closing PR here that updates the docs (apologies earlier, got a bit click happy :) ).

cc: @patriciasantaana for the docs updates

**Comment by cascadingstyletrees** [comment]
All of the information here has already been addressed either in Blog posts, or WAF docs.

I think one correction here is that Turnstile is a standalone/separate product that replaces traditional captcha services it's not automatically injected, you have to add the script to your page and validation in your webserver, it's a much more involved setup, however, further, Cloudflare runs all Challenges using Turnstile now days, so maybe that's where the confusion is.

So the takeaway here is, don't worry too much about Turnstile, but consider the many layers of security Cloudflare offers, since many of those could trigger Challenges.

So let's break down your question, you mentioned,

> I recently set up an email server (listmonk.app) on a subdomain and enabled the cloudflare proxy to protect my IP from DDoS attacks.
> 
> My concern is that when people click the "unsubscribe" links they will be presented with a captcha puzzle and will close the tab and click "spam" instead. 

If this happens, then you can see in your firewall events dashboard the reason for the block, and adjust the settings for that product, I wouldn't go changing too many settings before you notice an issue. Most of the time, human users will not see any challenges. 

You can also use Custom Rules with the Skip action to bypass Cloudflare Security features for a specific URL, like your unsubscribe URL, see https://developers.cloudflare.com/waf/custom-rules/skip/

> You can lower your security level to “Essentially off”, but that's not a good fix because it does it for the entire domain instead of just the subdomain that listmonk is installed on. 

Adjusting Security Level may be helpful, but false positives for human users are fairly rare, and usually it's because the IP has bad reputation. https://developers.cloudflare.com/waf/tools/security-level/#security-level 

> I know that [Cloudflare uses hcaptcha by default](https://blog.cloudflare.com/moving-from-recaptcha-to-hcaptcha/). I learned about turnstile and it seems to be the solution for this. But there is no simple checkbox in https://dash.cloudflare.com/ to switch a website or subdomain to turnstile instead of hcaptcha.

As discussed, we've completely phased out hCaptcha, and all Cloudflare challenges already use Turnstile, but the Turnstile Tab in the Cloudflare dashboard, is for the standalone Turnstile, so unless you are manually implementing Turnstile, focus on our Managed, Interactive, and Non-interactive Challenges.

https://developers.cloudflare.com/waf/reference/cloudflare-challenges/ is a good start to understand Cloudflare Challenges, as is the rest of the [WAF Dev Docs](https://developers.cloudflare.com/waf/).

I suggest also going through the Cloudflare Application Security Learning Paths: https://developers.cloudflare.com/learning-paths/application-security/

**Comment by cascadingstyletrees** [comment]
@kodster28 @patriciasantaana Do you see any opportunities for additional docs per the above info? If not, I think this is good to be closed.

**Comment by MaximilianKohler** [comment]
>All of the information here has already been addressed either in Blog posts, or WAF docs.

This is not sufficient. We shouldn't be expected to spend hours reading through blog posts and other docs for something as simple as being informed that Cloudflare is currently using turnstile so if we have our domain/subdomain proxied there's nothing we need to do. The searches I did brought me to the blog post saying that Cloudflare switched from recaptcha to hcaptcha.

I don't see any problem with adding some text _(to the locations I listed)_ saying _"Domains that are proxied by Cloudflare already use turnstile by default so no additional configuration is needed"_. 

>however, further, Cloudflare runs all Challenges using Turnstile now days, so maybe that's where the confusion is.

Yes, that's it. I came across no such information until I opened this issue.
