### ISSUE TITLE
Instructions for getting account ID may be incorrect

### ISSUE THREAD

**Issue by gar1t** [cloudflare/cloudflare-docs#12493]
### Example URL(s)

https://developers.cloudflare.com/fundamentals/setup/find-account-and-zone-ids/

### Actual Behavior

I found the information under **Workers and Pages**. I could not see an **API** section anywhere, though I may just have missed it.

### Expected Behavior

Docs instruct to look for **API** from "landing page". I couldn't find anything like that.

**Comment by kodster28** [comment]
Howdy @gar1t, think you might have missed the `select your account and domain` part of step 1 in that doc. The intention of the page (currently) is to help folks find their account/zone ids that are shown on the overview page of a specific zone/domain/website.

That being said, probably worth adding a callout for the account id info w/in the Workers and Pages area, since not everyone looking at it is going to have an associated zone. I'll push up a change addressing this early next week.

Thanks for raising!

**Comment by RDjarbeng** [comment]
I have a similar issue, 
I am following this page [Find account ID (Workers and Pages)](https://developers.cloudflare.com/fundamentals/setup/find-account-and-zone-ids/#find-account-id-workers-and-pages)

I can't find the 'account details' section to do step 4.  when on the 'workers and pages'. See screenshot. 
![image](https://github.com/user-attachments/assets/09a6c403-731b-4d8b-b7cb-2b46d0c307a1)
Seems that part might have changed and needs updating.

**Comment by RDjarbeng** [comment]
Someone commented in the [community](https://community.cloudflare.com/t/retrieve-account-id-to-create-first-zone/582994/8) that I can obtain this id from the URL. Which is not the best user experience
