### ISSUE TITLE
update: "Deploy a Blazor site"

### ISSUE THREAD

**Issue by gregorygandy** [cloudflare/cloudflare-docs#12573]
### Which Cloudflare product does this pertain to?

Pages

### Existing documentation URL(s)

https://developers.cloudflare.com/pages/framework-guides/deploy-a-blazor-site/

### What changes are you suggesting?

Issue: Deployment using the provided build script with the current .NET SDK (8.0) that is linked at the start of the page fails with "error NETSDK1045: The current .NET SDK does not support targeting .NET 8.0.  Either target .NET 7.0 or lower, or use a version of the .NET SDK that supports .NET 8.0.".

Suggested changes: 
- Update line 4 in the build script from `./dotnet-install.sh -c 7.0 -InstallDir ./dotnet` to `./dotnet-install.sh -c 8.0 -InstallDir ./dotnet`. 
- Indicate in the docs or build script that line 4 of the build script must be updated to reflect the current or desired .NET SDK.

**Comment by dario-piotrowicz** [comment]
Hello @gregorygandy 👋 

Thanks so much for the issue ❤️ , sorry it took us a while to get back to you 🙇 

I've opened #14293 to update the Blazor guide accordingly, if you want please feel free to have a look and let me know if you 're ok with the changes 🙂 

___

By the way, my opinion is that we should assume the usage of the latest .NET version instead of, as you suggested in your second bullet point, that other .NET SDK versions can be used.

Allowing people to choose older .NET SDK versions to me would increase our maintainability cost (we'd also have to document what versions are supported, potentially include version-specific troubleshooting info, etc...) and I hope that anyways using the latest SDK is not too strong of an assumption 🤔

People on an older version of the SDK could read our guide and try to use their SDK version and figure this out anyways, without us "officially" supporting that.

Given the fact that the SDK is a global program in your system I can see how people could need to stay on an older SDK version even though they are creating a brand new Blazor app here... maybe we could add an aside suggesting something along the lines of `if you can't use the latest SDK, you can try using an older one, remember to update the build.sh script` (which provides some help without overly committing on the solve SDKs support) 🤔 

what do you think? 🙂 

I'm also very keen to hear @kodster28's opinion on this 🙂
