### ISSUE TITLE
Documentation how to object to being classified as Potentially Automated Visitor

### ISSUE THREAD

**Issue by ProditorMagnus** [cloudflare/cloudflare-docs#12903]
### Which Cloudflare product(s) does this pertain to?

Turnstile

### Subject Matter

Error Code: 600010

### Content Location

https://developers.cloudflare.com/turnstile/reference/client-side-errors/

### Additional information

Error code collected from https://pp-attester-turnstile.research.cloudflare.com/challenge, real site just keeps looping.

**Comment by patriciasantaana** [comment]
Hi @ProditorMagnus ! Thank you for opening this issue. Troubleshooting 600*** errors have been documented on [Turnstile's list of error codes](https://developers.cloudflare.com/turnstile/reference/client-side-errors/#error-codes). I will close this now, but please feel free to ask questions or open a new issue.

**Comment by ProditorMagnus** [comment]
Currently documented Troubleshooting steps are from point of view of server. "Retry the challenge." part seems to happen, after some attempts https://pp-attester-turnstile.research.cloudflare.com/challenge opened in new tab.

However, I do not see how I could follow instruction to "verify the visitor otherwise.".

**Comment by ProditorMagnus** [comment]
I got access by copying over cookies
cf_clearance
__cf_bm
cf_chl_3

**Comment by ProditorMagnus** [comment]
@patriciasantaana looks like https://web-eid.eu/ extension breaks your validation. Maybe add it as possible reason.

**Comment by Endorakai** [comment]
Indeed.com has a 600010 error, which is why I am here (The only issue that contained my error I could find) despite it being "closed". It is not closed for me. Turnstile working properly everywhere else I have ran into it, just not Indeed.com. I don't understand why, and it is keeping me from all kinds of job opportunities, as this is my only device I have access to for PROPER internet browsing (both phone browsing, and the Indeed app is a complete joke.)

Xbox with default edge settings, Xbox allows no addons/extensions, no downloads, no vpns. Just browsing. ONLY browsing. There is not a single setting that either affects Cloudflare working, and what settings have ever existed hasn't been changed since the time it worked.

The Xbox Series X Edge browser and OS are compatible with all current "latest" websites on its own merits, and is locked down to prevent hacking the system. It is secure, and no known malware exist for the system as of this date.

A new issue cannot be created on this system as it ALSO requires turnstile passing. This will be the only way I can get help.

Session ID:
19DD6E7312BA62C1D73
Your IP Address:
(Private for this post)
Timestamp:
2026-04-29T01:42:53.348Z
Browser:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36 Edg/145.0.0.0
Turnstile Status:
loading
All Diagnostic Results
✅
Browser Version
Microsoft Edge v145 (supported)
✅
Cookies
Working correctly
✅
Automation Check
No automation detected
✅
System Clock
Clock synchronized
❌
Privacy Tools
Graphics Information Appears Fake
