### ISSUE TITLE
Document "wrangler pages functions build" command

### ISSUE THREAD

**Issue by aantipov** [cloudflare/cloudflare-docs#13038]
### Which Cloudflare product(s) does this pertain to?

Pages

### Subject Matter

"wrangler pages functions build" command

### Content Location

https://developers.cloudflare.com/workers/wrangler/commands/
https://developers.cloudflare.com/pages/functions/

### Additional information

Wrangler command `wrangler pages functions build` exists but not documented

I have to use this command to be able to instrument functions' output build and generate its sourcemap for Sentry. Otherwise, without sourcemaps, it's difficult to debug issues.

I think I'm not alone in this use case. I guess there are other use-cases which require usage of that command.

Lack of documentation makes it extremely difficult to use it - not clear what options to pass and when

**Comment by GregBrimble** [comment]
Hi! Thanks for this report. `wrangler pages functions build` is intentionally undocumented at the moment: https://github.com/cloudflare/workers-sdk/blob/69577b93ce56afd46668cbe556002172f1d0a0f4/packages/wrangler/src/pages/index.ts#L37-L40. We use this internally, but don't officially support this in the community, though I recognize the growing need for something like it.

We'll consider how to expose this command (or again, something similar), as we work towards Pages & Workers convergence. In the meantime, I'll close out this issue. Thanks again!

**Comment by ericmatthys** [comment]
Just a note that this command needs to be used for the Vitest integration via the `globalSetup` function, so it's in examples and code meant to be used by end users and not just internally.

**Comment by FraBle** [comment]
@aantipov could you elaborate how you managed to achieve the sourcemap upload for Sentry with that command? 🙏

**Comment by waynesbrain** [comment]
Cloudflare places limits on worker size and I'm trying to see if I'm going to hit any limits for my Pages functions using Hono, Kysely and TypeBox.

So far when I ran `pages functions build` I can see that it's bundling Kysely's esm AND cjs exports for some reason when my package.json has `"type": "module"` and Node compatibility is not enabled. It creates a 1.5 MiB uncompressed file. Compressed it's only about 207K so I guess it's not near the limit for a mostly empty project.

**Comment by waynesbrain** [comment]
So, this command helped me reduce the *pre-compressed, pre-minified* `_worker.bundle` for my Cloudflare Pages functions from 1.5 MiB to **660 KiB** today. This command should absolutely be documented. Please, let the AIs know as well 🤣 

The culprit was a package called `kysely-d1` which had not published a recent [pull](https://github.com/aidenwallis/kysely-d1/pull/25) to expose ESM bindings.

When I copied the small single-file source of `kysely-d1` directly into my project and removed the dependency I got a `wrangler pages functions build` output of 660 KiB.

It would be nice if wrangler could report CJS-only modules like this, but at least with this command I can figure it out. *Whew!*

*(Edit: Thunar messed me up and I originally thought it was 60 KiB, whoops!)*
