### ISSUE TITLE
incomplete rule id at WAF log

### ISSUE THREAD

**Issue by cjcfcode** [cloudflare/cloudflare-docs#13204]
### Which Cloudflare product does this pertain to?

WAF

### Existing documentation URL(s)

https://developers.cloudflare.com/waf/change-log/2024-02-26/

### What changes are you suggesting?

Not sure why the rule is incomplete such as "...1d870399"

**Comment by pedrosousa** [comment]
Since rule IDs are quite long, both the Developer Docs and the Cloudflare dashboard usually refer to the rule IDs using an abbreviated form, where only the last eight characters of the rule ID are shown. You can search for a rule in the dashboard using the "shortened" rule ID.

![image](https://github.com/cloudflare/cloudflare-docs/assets/680496/efab6cc2-23f7-43b1-97cb-e35f24a5472e)

The dashboard will show the complete rule ID as a tooltip when you hover a short rule ID. You also have the option to copy the full rule ID.

![image](https://github.com/cloudflare/cloudflare-docs/assets/680496/b8e1ac48-61be-4678-9f36-b7ab29b70b1a)

**Comment by pedrosousa** [comment]
Hi @cjcfcode 
A quick update: We've started using a new component in Dev Docs to display rule IDs (and ruleset IDs). We will still display the short version of the rule IDs in the documentation, but you can click the short ID to copy the **full** rule ID to your clipboard.

Here's an example page already using this component:
https://developers.cloudflare.com/waf/change-log/2024-04-15/
