### ISSUE TITLE
Request headers modification docs never mention that these are headers sent to origin server, not the client.

### ISSUE THREAD

**Issue by alex-jitbit** [cloudflare/cloudflare-docs#13328]
### Which Cloudflare product does this pertain to?

Fundamentals

### Existing documentation URL(s)

https://developers.cloudflare.com/rules/transform/response-header-modification/create-dashboard/
https://developers.cloudflare.com/rules/transform/response-header-modification/

### What changes are you suggesting?

Mention that the whole "header" functionality is for "origin <-> cloudflare"

I was looking for a way to add headers to USER repsonse, and Cloudflare offers no way to do this. But I wasted precious time reading the unrelevant docs

**Comment by pedrosousa** [comment]
To add headers to the **request** (Cloudflare --> origin server) you can use [request header modification rules](https://developers.cloudflare.com/rules/transform/request-header-modification/) instead of response header modification rules.

I'll try to clarify the context of which headers are being modified by each feature.
