### ISSUE TITLE
Feature request - AI non-chat completion API

### ISSUE THREAD

**Issue by Raskoll2** [cloudflare/cloudflare-docs#13901]
### Proposed changes

https://api.cloudflare.com/client/v4/

### Subject Matter

Can we get LLM completion without the chat template?

### Content Location

https://api.cloudflare.com/client/v4/

### Additional information

Sorry, this isn't really a docs thing, but I don't know where else to ask. I'm trying to use deepseek for fill in the middle code generation, but because the FIM template is wrapped in chat template the model returns 

Here is the corrected code:

\```python
{The full script}
\```

with every query. Is this by design so people don't use it as a free vscode copilot? Understandable if so, but there are good uses for general purpose models with no chat template as well, like an assistant writer in a book writing website or something. Maybe a completion only API could be restricted to non-code models.

Rather than 
json = '{ "messages": [...]}'

I propose substituting "messages" for "complete", and taking a string rather than array. This seems simple to implement and may be in the works already, I'd be very grateful if it came to fruition.

Thanks,
Harper

**Comment by craigsdennis** [comment]
Hi @Raskoll2 I think you probably want to use an [unscoped prompt](https://developers.cloudflare.com/workers-ai/models/deepseek-coder-6.7b-instruct-awq/#unscoped-prompts). Instead of `messages` you can pass `prompt`

Related: I was able to use FITM in the [Deepseek coder tutorial](https://developers.cloudflare.com/workers-ai/tutorials/explore-code-generation-using-deepseek-coder-models/#fill-in-the-middle-code-completion). It does make use of the messages style.

**Comment by Raskoll2** [comment]
Thanks, it seems I didn't look hard enough.
