### ISSUE TITLE
Cloudflare DNS uses wrong MIME headers for "application/dns+json" as per RFC 8427

### ISSUE THREAD

**Issue by cookiengineer** [cloudflare/cloudflare-docs#1398]
### Expected Behavior

The following should work, but it doesn't. Cloudflare DNS uses a custom non-registered MIME type `application/dns-json` which should be `application/dns+json` as per [RFC draft 8427](https://datatracker.ietf.org/doc/html/rfc8427).

### Actual Behavior

The following will return an empty reply as it is ignored.

```
curl -H 'accept: application/dns+json' 'https://cloudflare-dns.com/dns-query?name=example.com&type=AAAA'
```

**Comment by kodster28** [comment]
Howdy @cookiengineer! Are you referencing our API docs? Or a specific page within this repo?

**Comment by kodster28** [comment]
Just a small bump on this, @cookiengineer. I'm afraid we don't have enough information to take action on this issue w/o a response.

**Comment by cookiengineer** [comment]
Hey, I was actually writing about this in the 1.1.1.1 repository, as well.

( https://github.com/cloudflare/1.1.1.1/issues/120 )

@vavrusa cleared it up and mentioned that the MIME type used by cloudflare is `application/dns-json` and not `application/dns+json` like in the current specification ( https://datatracker.ietf.org/doc/html/rfc8427#section-7.1 ).

So this is both an implementation issue and a documentation issue, as the current cloudflare implementation does not support MIME headers as the specification (RFC 8427) describes as a MUST.

**Comment by marciocloudflare** [comment]
Hi @cookiengineer. We've checked in with the Engineering team about this and Cloudflare's DNS over HTTPS endpoint also supports JSON format for querying DNS data. For lack of an agreed upon JSON schema for DNS over HTTPS in the IETF, Cloudflare has chosen to follow the same schema as Google's DNS over HTTPS resolver.
Since there's nothing we can really do about this on the docs side, going to go ahead and close out this issue.
