### ISSUE TITLE
Cloudflare DNS uses wrong URL path for resolve as JSON API (/resolve redirects to /)

### ISSUE THREAD

**Issue by cookiengineer** [cloudflare/cloudflare-docs#1399]
### Expected Behavior

As per https://developers.google.com/speed/public-dns/docs/doh and [RFC8484](https://datatracker.ietf.org/doc/html/rfc8484) the `/dns-query` API accepts only the DNS UDP wireformat (`application/dns-udpwireformat` as per RFC with a base64url encoded `?dns=` parameter).

The `/resolve` path, however, is meant for the JSON API, using the `application/dns+json` header. On Cloudflare DNS, this is incorrectly supported via the `/dns-query` path, and the `/resolve` path is redirecting to `/`.

I opened up [another issue](https://github.com/cloudflare/cloudflare-docs/issues/1398) regarding the `dns+json` vs. `dns-json` quirks that Cloudflare uses in a spec-incompliant manner.

**Comment by kodster28** [comment]
Howdy @cookiengineer! Are you referencing our API docs? Or a specific page within this repo?

**Comment by kodster28** [comment]
Just a small bump on this, @cookiengineer. I'm afraid we don't have enough information to take action on this issue w/o a response.

**Comment by marciocloudflare** [comment]
Hi @cookiengineer. We've checked in with the Engineering team about this and Cloudflare's DNS over HTTPS endpoint also supports JSON format for querying DNS data. For lack of an agreed upon JSON schema for DNS over HTTPS in the IETF, Cloudflare has chosen to follow the same schema as Google's DNS over HTTPS resolver.
Since there's nothing we can really do about this on the docs side, going to go ahead and close out this issue.
