### ISSUE TITLE
Consider adding Rust web app tutorial based on @mehmetcansahin/cf-workers-web-app

### ISSUE THREAD

**Issue by mehmetcansahin** [cloudflare/cloudflare-docs#14]
Hello,

I prepared a simple web app template by using rust on Cloudflare workers. Do you think it would make sense to add this as documentation?

[cf-workers-web-app](https://github.com/mehmetcansahin/cf-workers-web-app)

**Comment by kristianfreeman** [comment]
hey @mehmetcansahin, sorry we missed this! it looks like the project hasn't been updated since 12/2020, would love to get a new version in the docs if you're interested - feel free to open a pull request to our [quick starts page](https://github.com/cloudflare/cloudflare-docs/blob/production/products/workers/src/content/get-started/quickstarts.md). closing in the meantime in favor of a newer ticket (preferably PR!) if you'd like to do that
