### ISSUE TITLE
Rewrite rules lack examples

### ISSUE THREAD

**Issue by cpubaker** [cloudflare/cloudflare-docs#14069]
### Existing documentation URL(s)

https://developers.cloudflare.com/rules/transform/url-rewrite/examples/

### What changes are you suggesting?

For three days I am trying to create a simple rule that will transform 'subdomain.mydomain.com' to 'subdomain.mydomain.com/domainFolder'. 
Nothing works. The examples provided are all irrelevant. 
There is also nothing on how you may get any related logs or troubleshoot your rules.

**Comment by pedrosousa** [comment]
Hi @cpubaker 

First, I'd clarify your use case: do you want your website visitors to see the updated URL in their browser? If the answer is yes, then you should use a **URL redirect** (probably through [Single Redirects](https://developers.cloudflare.com/rules/url-forwarding/single-redirects/)) instead of a URL rewrite. This difference is covered in the [URL rewrites introduction](https://developers.cloudflare.com/rules/transform/url-rewrite/).

Assuming you really want to rewrite the URL (an invisible change to your website visitors), I'd clarify the following next:
A) Do you want to rewrite the URL from the home page to the `/domainFolder` folder (a static rewrite)?
or
B) Do you want to rewrite the URL of all pages in your website's root folder to the `/domainFolder` folder (a dynamic rewrite, where you enter a rewrite expression)?

Regarding troubleshooting, you can use [Cloudflare Trace](https://developers.cloudflare.com/fundamentals/basic-tasks/trace-request/) to find if a rule of a Cloudflare product is triggering for a given URL. It supports both URL rewrite rules and URL redirects.

**Comment by cpubaker** [comment]
> Hi @cpubaker
> 
> First, I'd clarify your use case: do you want your website visitors to see the updated URL in their browser? If the answer is yes, then you should use a **URL redirect** (probably through [Single Redirects](https://developers.cloudflare.com/rules/url-forwarding/single-redirects/)) instead of a URL rewrite. This difference is covered in the [URL rewrites introduction](https://developers.cloudflare.com/rules/transform/url-rewrite/).
> 
> Assuming you really want to rewrite the URL (an invisible change to your website visitors), I'd clarify the following next: A) Do you want to rewrite the URL from the home page to the `/domainFolder` folder (a static rewrite)? or B) Do you want to rewrite the URL of all pages in your website's root folder to the `/domainFolder` folder (a dynamic rewrite, where you enter a rewrite expression)?
> 
> Regarding troubleshooting, you can use [Cloudflare Trace](https://developers.cloudflare.com/fundamentals/basic-tasks/trace-request/) to find if a rule of a Cloudflare product is triggering for a given URL. It supports both URL rewrite rules and URL redirects.

Thank you for your reply @pedrosousa. I do want to configure a REWRITE rule, the redirect works fine but it is not what I want.
For me it does not matter if it a static rewrite or a dynamic one. In my scenario I may use both of them.

Thank you for pointing out the 'Cloudflare Trace' but at the moment it is broken. As I may understand the feature is still in beta.

Anyway thick 'ticket' was not related to the issue itself but to the documentation. It lacks simple examples, everything it has are rather complicated scenarios.
