### ISSUE TITLE
Angular deployment build directory changed

### ISSUE THREAD

**Issue by larsjuhw** [cloudflare/cloudflare-docs#14187]
### Existing documentation URL(s)

https://developers.cloudflare.com/pages/framework-guides/deploy-an-angular-site/

### What changes are you suggesting?

The docs currently note that the `outputPath` value in `angular.json` should be the same as the "Build directory" setting of the Cloudflare pages configuration. However, since Angular 17, build output for the browser is now placed in a `browser` folder inside the build output path, even if SSR is disabled. Therefore, when following these current docs with Angular 17, the deployment will not work because the indexx.html file is inside the browser folder. Setting the "Build directory" setting to `{outputPath}/browser` seems to fix the issue.

### Additional information

Related issue: https://github.com/angular/angular-cli/issues/26304

**Comment by dario-piotrowicz** [comment]
Thanks a lot for the issue @larsjuhw 🙏 

Our Angular guide was quite outdated, I'm updating it in #14224, the changes there should solve the issue you're mentioning (removing the `angular.json` section entirely since that is already set up correctly by C3 for you).

Please have a look at the [PR's preview guide](https://e01c4f81.cloudflare-docs-7ou.pages.dev/pages/framework-guides/deploy-an-angular-site/) and let me know if you find the guide correct now or if you think that something should be changed there 🙏
