### ISSUE TITLE
Add note to node-postgres tutorial to highlight it doesn't work on Pages

### ISSUE THREAD

**Issue by petebacondarwin** [cloudflare/cloudflare-docs#14362]
### Existing documentation URL(s)

https://developers.cloudflare.com/workers/tutorials/postgres/

### What changes are you suggesting?

Add a note to the top of the tutorial that calls out the fact that this approach only works in a Worker and not in a Pages project.

### Additional information

See https://github.com/cloudflare/workers-sdk/pull/2541#issuecomment-1964627452

**Comment by webdeb** [comment]
Its not from this repo, but its related. Its unclear how to use pg in a next-on-pages project. Dev & Deploy.

**Comment by KimJ15** [comment]
@petebacondarwin I read through the tutorial and I thought it was pretty clear that this was for Cloudflare Workers (it's in the Workers space, it clearly calls out the product name, etc.). Not sure if the content was updated and that's why it's clear to me?

If updates should be made, feel free to suggest a PR.

**Comment by petebacondarwin** [comment]
Looks like it was heavily updated in Aug and Sep. Thanks for checking.
