### ISSUE TITLE
Where is new Page rules documentation, No examples only theories, very worst experience, wasted my 8 hours

### ISSUE THREAD

**Issue by rishavayadav** [cloudflare/cloudflare-docs#14824]
### Proposed changes

https://developers.cloudflare.com/rules/

### Subject Matter

Page Rules/Rules

### Content Location

I want old page rules back. they are easy to apply. we wasted 8 hours in redirecting subdomain to root in new page rule, we saw many videos on youtube, nothing found. In the end we add old page rule, that works within a second.

New Rules are very confusing and we still not know ABC of new rules.

Please make a user friendly documentation not bot friendly.

**Comment by Cherry** [comment]
cc @nikitacano.

Related: https://github.com/cloudflare/cloudflare-docs/issues/14737

**Comment by nikitacano** [comment]
@rishavayadav, what kind of redirect were you trying to configure? We already have plans to add more examples to https://developers.cloudflare.com/rules/reference/page-rules-migration/#migrate-forwarding-url and will use your feedback to improve this section.

**Comment by fmonts** [comment]
I agree the new rules are very badly designed. 

They ask you to choose between "static" and "dynamic" with no description at all on what those terms are supposed to mean, since there is no such terminology in HTTP standards. 

For example I just want to redirect `domain1.com/*` to `domain2.com/$1`, is that a "static" or "dynamic" redirect? It was very simple with the old page rules. 
Or another common example is to add/remove www, so I want to redirect `www.domain1.com/*` to `https://domain1.com/$1`

And besides the static/dynamic, it's not clear at all how to write the rules.

**Comment by pedrosousa** [comment]
Hello!
Since this issue was opened, we've done numerous updates to our public documentation. We've also introduced wildcard matching support on all Cloudflare plans so that rule expressions are easier to write.
Also, Page Rules are not going away for the time being. And when the time comes, Cloudflare will perform the migration for you.

If you have other concerns, you can check the Community thread about the future of Page Rules and the features that will replace them:
https://community.cloudflare.com/t/page-rules-are-now-deprecated-without-good-replacements/656245/1
