### ISSUE TITLE
Vague "Statement too long" error when importing large SQL files into D1

### ISSUE THREAD

**Issue by t-rupe** [cloudflare/cloudflare-docs#15053]
### Proposed changes

https://developers.cloudflare.com/d1/build-with-d1/import-data/

I want to suggest adding a less vague error description for the "Statement too long" error message received when you go to import a large sqlite database file to Cloudflare D1 using Wrangler. It'd be helpful to include somewhere the maximum size of a statement, whether it's the data size or lines of SQL. Additionally, it would be good to have documentation explaining why it occurred and adding a simple troubleshooting suggestion to fix the issue, which can easily be fixed by converting a large statement into multiple statements or simply reducing the file size via lines of code or otherwise.  

### Subject Matter

An explanation of the error, step-by-step instructions to break down large SQL statements, and offering code examples to demonstrate the suggested approaches.

### Content Location

https://developers.cloudflare.com/d1/build-with-d1/import-data/#troubleshooting

**Comment by Oxyjun** [comment]
Update: Since this Issue, we have added a new section for troubleshooting this particular error [here](https://developers.cloudflare.com/d1/build-with-d1/import-export-data/#resolve-statement-too-long-error)

Also, our maximum SQL statement length, and our maximum row lengths are both documented in out [limits](https://developers.cloudflare.com/d1/platform/limits/) page.

**Comment by Oxyjun** [comment]
There is another issue/internal effort to consolidate D1 errors in one page.

Related GH issue: https://github.com/cloudflare/cloudflare-docs/issues/18485

Closing this issue for now.
