### ISSUE TITLE
A/B testing JS stacktrace exception occurs

### ISSUE THREAD

**Issue by ZengTianShengZ** [cloudflare/cloudflare-docs#15117]
### Example URL(s)

https://developers.cloudflare.com/workers/examples/ab-testing/

### Actual Behavior

```
<--- Last few GCs --->

[68627:0x120040000]    22020 ms: Mark-Compact 1399.5 (1413.5) -> 1392.8 (1415.0) MB, pooled: 0 MB, 1979.42 / 0.00 ms  (average mu = 0.301, current mu = 0.006) allocation failure; scavenge might not succeed
[68627:0x120040000]    24145 ms: Mark-Compact 1400.8 (1415.0) -> 1394.1 (1416.3) MB, pooled: 0 MB, 2122.46 / 0.00 ms  (average mu = 0.172, current mu = 0.001) allocation failure; scavenge might not succeed


<--- JS stacktrace --->

workerd/jsg/setup.c++:35: fatal: V8 fatal error; location = Reached heap limit; message = : allocation failed: JavaScript heap out of memory
workerd/util/symbolizer.c++:96: warning: Not symbolizing stack traces because $LLVM_SYMBOLIZER is not set. To symbolize stack traces, set $LLVM_SYMBOLIZER to the location of the llvm-symbolizer binary. When running tests under bazel, use `--test_env=LLVM_SYMBOLIZER=<path>`.
*** Received signal #6: Abort trap: 6
stack: 
```

### Expected Behavior

Expect A/B workers to work properly

### Additional information

This code should be called recursively, resulting in JS stacktrace

```
async fetch(req): Promise<Response> {
      ...
      return fetch(req);
      ...
}

**Comment by kodster28** [comment]
Howdy @ZengTianShengZ, asked around internally and this example works correctly when proxying a request to your origin. In a live Worker, a Worker fetching itself is the intended way to reach the origin behind the Worker.

The reason you're seeing those exceptions is because the behavior of a Worker is different during local development.

In local development, there is no origin - you'll need to have routes in `wrangler.toml`, a `dev.host` entry or use the `--local-upstream`/`--upstream-protocol` flags.
