### ISSUE TITLE
Document what causes you to strong-arm companies into enterprise

### ISSUE THREAD

**Issue by Devlyn-Nelson** [cloudflare/cloudflare-docs#15234]
### Proposed changes

[This](https://robindev.substack.com/p/cloudflare-took-down-our-website) is ridiculous, just like how hard it is to submit feedback. I was just thinking last week that you were a nicer company than google, but... And i didn't want to use my account for this feedback in fear of my account being deleted because apparently you guys do stuff like that (that is not the only article describing your bullying practices). You should document that you will strong arm people into enterprise.

### Subject Matter

You guys being evil

### Content Location

Anywhere

### Additional information

Please don't be a bully.

**Comment by piyushzingade** [comment]
What is issues can you please tell me

**Comment by kodster28** [comment]
Howdy @Devlyn-Nelson,

We have millions of customers: from small businesses and individual developers to approximately 30 percent of the Fortune 500. Today, more than 20 percent of the web relies directly on Cloudflare’s services. 

We strive to be transparent in our policies and uniform in enforcing them. We can't discuss a specific customer due to our commitment to confidentiality. However we can say that when a customer violates our [terms of service (TOS)](https://www.cloudflare.com/website-terms/) we do provide ample notice and take action needed to protect our service.

Going to close this out so we have more space to pay attention to and fix issues in our docs.
