### ISSUE TITLE
The website does not open in Kazakhstan without VPN.

### ISSUE THREAD

**Issue by StrahCat** [cloudflare/cloudflare-docs#15244]
### Example URL(s)

https://aromatniymir.com/ . https://aromatniymir.kz/
![йцуйц](https://github.com/cloudflare/cloudflare-docs/assets/88330699/7c58f223-e0ef-42aa-9d6f-c8dc89257f04)

### Actual Behavior

Hello, since yesterday we've been facing an issue where the website doesn't open without VPN in Kazakhstan. The domain aromatniymir.com is hosted with you, and we were advised to contact you regarding this problem. Please help us resolve the issue.

### Expected Behavior

Hello, since yesterday we've been facing an issue where the website doesn't open without VPN in Kazakhstan. The domain aromatniymir.com is hosted with you, and we were advised to contact you regarding this problem. Please help us resolve the issue.

### Additional information

We have two domains: 1) aromatniymir.kz and 2) aromatniymir.com. The first domain is redirecting to the second one. The provider of the first domain indicated that the issue lies with you. Please check and resolve this problem.

**Comment by StrahCat** [comment]
Perhaps the website was taken down by a DoS attack.

**Comment by kodster28** [comment]
Howdy @StrahCat, we can't do much on this end because this is a documentation repo.

I'd encourage you to reach out to [Cloudflare Support](https://developers.cloudflare.com/support/contacting-cloudflare-support/) or the [Cloudflare Community](https://community.cloudflare.com/) about your problem. We can really only help with pure documentation issues.
