### ISSUE TITLE
erreur

### ISSUE THREAD

**Issue by Mebstyle** [cloudflare/cloudflare-docs#15241]
### Example URL(s)

![image](https://github.com/cloudflare/cloudflare-docs/assets/129989744/636b6a7d-0e61-4a0e-822e-00cfa8ad87d3)
https://manga-scantrad.io/manga/leveling-up-with-a-sword/chapitre-43/?__cf_chl_tk=cnQCFYDnA_NRT8gB4grYN_4NuRfvUAH8wpO5HZs18wA-1718954613-0.0.1.1-4863

### Actual Behavior

je n'arrive plus à accéder à https://manga-scantrad.net/ 
![image](https://github.com/cloudflare/cloudflare-docs/assets/129989744/fc0a6422-222f-4ed0-b4a3-b115af1db093)

### Expected Behavior

j'aime relire mes mangas au quotidien

**Comment by kodster28** [comment]
Howdy @Mebstyle, unfortunately that's due to an issue with the underlying site's configuration.

Your best bet is to reach out to the site owner letting them know that you're experiencing [520 errors](https://developers.cloudflare.com/support/troubleshooting/cloudflare-errors/troubleshooting-cloudflare-5xx-errors/#error-520-web-server-returns-an-unknown-error).
