### ISSUE TITLE
RPC and compatibility_date

### ISSUE THREAD

**Issue by stephen-hardy** [cloudflare/cloudflare-docs#15256]
### Existing documentation URL(s)

https://developers.cloudflare.com/workers/runtime-apis/rpc/
https://blog.cloudflare.com/javascript-native-rpc (not documentation, but please make an edit here too)

### What changes are you suggesting?

Please make a reference to the need to update the compatibility date in order to use this feature. I started testing RPC by using a quick test worker, created in the browser - therefore, no (apparent) Wrangler. It appears that such workers always use the latest compatibility date, so RPC was available to me right after I read the blog post and all worked great! Then, I tried to use RPC in Pages (created before RPC rolled out) and burnt a whole bunch of time with error messages saying my methods did not exist. 

I knew about compatibility dates, as I had ran across them in the documentation, but they did not come to mind for this issue. When I had looked at the change log for compatibility dates - before RPC existed - very few of the changes seemed like they'd be of any consequence. I thought, why would I ever care about this? These are tiny changes. And, what's more, most Pages don't have a wrangler.toml, as that is still in Beta. The setting for Pages compatibility dates is buried in the settings, inside functions, and many people would not have reason to go there.

People who create new Pages today will be fine, as they get a date after RPC rolled out. People who work with Workers via Wrangler a lot may be fine because they are more familiar with what a toml has and what compatibility_date means. But, even then, I think many would agree that no compatibility date change is nearly as impactful as this one. This one is revolutionary to how a developer uses the Cloudflare platform. And, for those that created a Pages instance before it rolled out, it is locked behind a setting that is either unknown or known for making very small changes.

For a while I wondered if RPC wasn't available in Pages, because I could find any documentation or reference in the blog post to it being applicable. I know that Pages is based off of Workers, but after hours of trying to figure out why Pages wouldn't behave similarly to my test Worker that was working perfectly, I started to entertain the possibility that Pages was a neglected platform and did not get the new features that Workers did. 

So, maybe I'm just especially dense, but please help people like me understand how to use this wonderful feature! I may not be the only person struggling with this: https://community.cloudflare.com/t/service-binding-pages-function-to-worker-cant-call-path/647192/2

I know this repo is only for the documentation, but I'd ask that an edit is made to the blog post to ensure people know they have to update compatibility date. Hardly anything else in the changelog is what I'd classify as a feature. Most things are compliance, cleanup, etc. I don't think anybody is used to changing compatibility date to enable a major feature addition.

**Comment by abohossny** [comment]
Where is the compatibility date, click on it data

احصل على Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Stephen Hardy ***@***.***>
Sent: Saturday, June 22, 2024 10:29:11 AM
To: cloudflare/cloudflare-docs ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [cloudflare/cloudflare-docs] RPC and compatibility_date (Issue #15256)


Existing documentation URL(s)

https://developers.cloudflare.com/workers/runtime-apis/rpc/
https://blog.cloudflare.com/javascript-native-rpc (not documentation, but please make an edit here too)

What changes are you suggesting?

Please make a reference to the need to update the compatibility date in order to use this feature. I started testing RPC by using a quick test worker, created in the browser - therefore, no (apparent) Wrangler. It appears that such workers always use the latest compatibility date, so RPC was available to me right after I read the blog post and all worked great! Then, I tried to use RPC in Pages (created before RPC rolled out) and burnt a whole bunch of time with error messages saying my methods did not exist.

I knew about compatibility dates, as I had ran across them in the documentation, but they did not come to mind for this issue. When I had looked at the change log for compatibility dates - before RPC existed - very few of the changes seemed like they'd be of any consequence. I thought, why would I ever care about this? These are tiny changes. And, what's more, most Pages don't have a wrangler.toml, as that is still in Beta. The setting for Pages compatibility dates is buried in the settings, inside functions, and many people would not have reason to go there.

People who create new Pages today will be fine, as they get a date after RPC rolled out. People who work with Workers via Wrangler a lot may be fine because they are more familiar with what a toml has and what compatibility_date means. But, even then, I think many would agree that no compatibility date change is nearly as impactful as this one. This one is revolutionary to how a developer uses the Cloudflare platform. And, for those that created a Pages instance before it rolled out, it is locked behind a setting that is either unknown or known for making very small changes.

For a while I wondered if RPC wasn't available in Pages, because I could find any documentation or reference in the blog post to it being applicable. I know that Pages is based off of Workers, but after hours of trying to figure out why Pages wouldn't behave similarly to my test Worker that was working perfectly, I started to entertain the possibility that Pages was a neglected platform and did not get the new features that Workers did.

So, maybe I'm just especially dense, but please help people like me understand how to use this wonderful feature! I may not be the only person struggling with this: https://community.cloudflare.com/t/service-binding-pages-function-to-worker-cant-call-path/647192/2

I know this repo is only for the documentation, but I'd ask that an edit is made to the blog post to ensure people know they have to update compatibility date. Hardly anything else in the changelog is what I'd classify as a feature. Most things are compliance, cleanup, etc. I don't think anybody is used to changing compatibility date to enable a major feature addition.

Additional information

No response

**Comment by ToriLindsay** [comment]
Thank you for your feedback! I have added a note to the article and forwarded the blog post update request onto the appropriate team.

**Comment by stephen-hardy** [comment]
This is perfect, thank you!
