### ISSUE TITLE
Integrating Cloudflare to my wordpress website.

### ISSUE THREAD

**Issue by Willzthegreat** [cloudflare/cloudflare-docs#15314]
### Example URL(s)

https://www.mbmnig.com/

### Actual Behavior

I recently integrated my company's website with Cloudflare optimized processing, but, I've been experiencing an Error 1000 on the site ever since.

### Expected Behavior

Expected the site's performance to be better at least close to being optimized.

**Comment by kodster28** [comment]
Howdy @Willzthegreat, not sure if you've checked out our documentation on [WordPress](https://developers.cloudflare.com/automatic-platform-optimization/)?

If that doesn't help you, your best bet would be reaching out to the [Cloudflare Community](https://community.cloudflare.com) since we can't provide tech support here (this is just a documentation repo).
