### ISSUE TITLE
can't open my website, it appears "  頁面重新導向不正確  連線到 www.eherber.com 時發生錯誤。      有時候停用或拒絕接受 Cookie 會造成此問題。

### ISSUE THREAD

**Issue by eherber-co** [cloudflare/cloudflare-docs#15456]
### Example URL(s)

頁面重新導向不正確

連線到 www.eherber.com 時發生錯誤。

    有時候停用或拒絕接受 Cookie 會造成此問題。

### Actual Behavior

頁面重新導向不正確

連線到 www.eherber.com 時發生錯誤。

    有時候停用或拒絕接受 Cookie 會造成此問題。

### Expected Behavior

頁面重新導向不正確

連線到 www.eherber.com 時發生錯誤。

    有時候停用或拒絕接受 Cookie 會造成此問題。

### Additional information

pls check for us what is going on?  How to fix it ?

**Comment by pedrosousa** [comment]
Hi @eherber-co
Unfortunately, we can't help much with your issue since this is a repository for problems with our documentation.

We recommend that you check the following pages and try the solutions presented there:
* [TOO_MANY_REDIRECTS](https://developers.cloudflare.com/ssl/troubleshooting/too-many-redirects/) 
* [Community Tip - Fixing ERR TOO MANY REDIRECTS](https://community.cloudflare.com/t/community-tip-fixing-err-too-many-redirects/42335/1)

If you can't solve your issue with the help of these resources, you can [contact Cloudflare Support](https://developers.cloudflare.com/support/contacting-cloudflare-support/) if you're on a paid plan, or reach out to the [Cloudflare Community](https://community.cloudflare.com/) if you're on a Free plan.
