### ISSUE TITLE
Escaping special characters in DNS analytics queries

### ISSUE THREAD

**Issue by yesoreyeram** [cloudflare/cloudflare-docs#15615]
### Proposed changes

- https://developers.cloudflare.com/dns/reference/analytics-api-properties/#filters
- https://developers.cloudflare.com/api/operations/dns-analytics-table

### Subject Matter

Escaping the query paramets

### Content Location

same document but in seperate section 

### Additional information

Currently the DNS Analytics API docs doen't instruct how to escape the the special characters such as `*`. For example, when using [dns analytics](https://developers.cloudflare.com/dns/reference/analytics-api-properties/#filters) [api](https://developers.cloudflare.com/api/operations/dns-analytics-table), and passing `filters` parameters such as `queryName==*.example.app,queryName==www.example.app`, the URL fails with the error **found \"*\", expected literal**

<img width="1162" alt="image" src="https://github.com/user-attachments/assets/16c6f15e-bb20-44e9-a43c-cfbaf3c2d58e">

**Comment by ghost** [comment]
I don't think this is an escaping issue, just a bug/limitation of our API where `*` can't start an identifier.

We encourage everyone to move to [GraphQL](https://developers.cloudflare.com/analytics/graphql-api/) but we'll get this fixed in the [old API](https://developers.cloudflare.com/dns/reference/analytics-api-properties/) for now. Please try again in ~2 weeks.

Closing this since it's not a documentation issue.

**Comment by ghost** [comment]
Asterisk/wildcard characters in query names should be supported now. Please try again when you get a chance!
