### ISSUE TITLE
Specify which domain name to use in Android Private DNS settings for DOH vs DOT 

### ISSUE THREAD

**Issue by bsmith75** [cloudflare/cloudflare-docs#16436]
### Existing documentation URL(s)

https://developers.cloudflare.com/1.1.1.1/setup/android/

### What changes are you suggesting?

The page suggests to use one.one.one.one which is correct if you want DOT. Android 11+ will use DOH3 if the hostname cloudflare-dns.com is provided.

**Comment by RebeccaTamachiro** [comment]
👋 @bsmith75 Thanks for reaching out! I have checked with the team and got confirmation that `one.one.one.one` supports DoH and works on Android. Since we only take care of the documentation in this repo, I will close this issue. Please reach out to [community.cloudflare.com](http://community.cloudflare.com/) with more details if the issue persists.

**Comment by bsmith75** [comment]
Android is hard coded to use DOH only when dns.google or cloudflare-dns.com is entered into private DNS settings. Any other domain name, including one.one.one.one, is treated as a DOT server.
