### ISSUE TITLE
"Enable Web Analytics" doc for Cloudflare Pages seems to give incorrect information

### ISSUE THREAD

**Issue by liamness** [cloudflare/cloudflare-docs#17187]
### Existing documentation URL(s)

https://developers.cloudflare.com/pages/how-to/web-analytics/
https://github.com/cloudflare/cloudflare-docs/blob/production/src/content/docs/pages/how-to/web-analytics.mdx

### What changes are you suggesting?

I can't successfully follow the "one click setup" method described. The "manage" menu option is not there, and if it has been moved / renamed I can't seem to find it. Could you please investigate this, and update the docs accordingly?

### Additional information

Here's a screenshot of what I see in the overview page of my project. There is no "manage" menu option.

![image](https://github.com/user-attachments/assets/d63d99fe-3e04-48e7-85fa-d55cde170e0a)

**Comment by ghvcs** [comment]
I have the same issue, cannot find "Manage" menu => cannot enable/disable Web Analytics anymore

**Comment by Yezhixue** [comment]
我也遇到了一样的问题cf里面无法解析wed文档的正确信息直接把我搞崩溃了创健项目也是显示wed文档无法显示解析不出来这个CF就等于废了用不了现在

**Comment by Yezhixue** [comment]
我也遇到了一样的问题cf里面无法解析WEd文档的正确信息直接把我搞崩溃了创健项目也是显示wed文档无法显示解析不出来这个CF就等于废了用不了现在

**Comment by Yezhixue** [comment]
我也遇到了同样的问题cf里面无法解析WEd文档的正确信息直接把我搞崩溃了创健项目也显示了wed文档无法显示解析不出来这个CF就等于废了用不了现在

**Comment by Yezhixue** [comment]
这个CF号等于废了呀大老有木有解决办法呀！

**Comment by liamness** [comment]
I'm not sure if this was here when I previously checked, but it seems that web analytics can be enabled from the metrics tab.

![image](https://github.com/user-attachments/assets/8f534f38-82ee-4657-b6ff-1fdc1bb8182c)

**Comment by markjmiller** [comment]
Yes that's the component's new home! Updating docs here https://github.com/cloudflare/cloudflare-docs/pull/17928

**Comment by brettwillis** [comment]
This mechanism uses manual JS snippet installation (just automatically includes it on deploy I guess), which we could do manually anyway. 

This loads the beacon from `static.cloudflareinsights.com` rather than our own domain's `/cdn-cgi/...`. Is it impossible to proxy via our own domain with Cloudflare Pages on a custom domain?

I'd like to see documentation for an option to manually including a snippet and configuring it to proxy via `/cdn-cgi/...` rather than `static.cloudflareinsights.com`.
