### ISSUE TITLE
Disable "Linkify"

### ISSUE THREAD

**Issue by aaron-ruby-df** [cloudflare/cloudflare-docs#175]
When contributing to Developer Docs, I want the docs engine to disable automatic linkification of domain/website names so that I can refer to specific sites and domains in content without creating links.

* A key use case here is for example.com, which we should be able to render in content as regular text, without hyperlinking or text decoration.

**Comment by adamschwartz** [comment]
I would wager than more often then not, link text ought to be made into a link. Linkifying Markdown text is also the default behavior on GitHub, where many folks may come to preview/edit their content.

My recommendation would be similar to [this StackOverflow response](https://stackoverflow.com/questions/25706012/how-do-i-prevent-auto-generated-links-in-the-github-wiki/25707855#25707855). Depending on the context and what’s needed, you have a few options:

1. Use an inline code block `https://example.com`.

2. Add an inline element to trick the parser, e.g. `example<span>.</span>com`.

3. Change `.` to `[dot]`, e.g. "Email me at me@example[dot].com".

All of these approaches are reasonable to me, and don’t seem particularly burdensome to authors. Please let me know if you disagree. Otherwise I’ll close this issue as `wontfix`.
