### ISSUE TITLE
Excluding `/cdn-cgi/challenge-platform/` not enough to unblock JS challenge 

### ISSUE THREAD

**Issue by nisbet-hubbard** [cloudflare/cloudflare-docs#17786]
### Existing documentation URL(s)

https://developers.cloudflare.com/waf/reference/cloudflare-challenges/#custom-content-security-policy-not-supported

### What changes are you suggesting?

Trying to use the current workaround in Safari

> If you are setting a CSP using Transform Rules for your entire website, you should [exclude URI paths starting with /cdn-cgi/challenge-platform/](https://developers.cloudflare.com/rules/reference/troubleshooting/#interaction-between-cloudflare-challenges-and-rules-features) in the rule expression to avoid issues with challenges.

I got the following error

> EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' 'unsafe-inline' https://static.cloudflareinsights.com".

After adding `'unsafe-eval'` I still got white screen, which I resolved by using `worker-src 'self' blob:;`.

After doing that, I got

> Please unblock challenges.cloudflare.com to proceed.

In sum, to get the challenge page to display in Safari, `script-src 'self' 'unsafe-eval' https://challenges.cloudflare.com; frame-src 'self' https://challenges.cloudflare.com; worker-src 'self' blob:;` are required on the protected page at the very least.

Note that excluding `/cdn-cgi/challenge-platform/` doesn’t work because the above-mentioned CSP directives have to be set _on the protected page_ rather than the challenge page.

**Comment by pedrosousa** [comment]
Hi @nisbet-hubbard 

I checked internally and we couldn't identify any issues in the Cloudflare-issued challenge pages (or in pages protected by Cloudflare challenges) from what you described.
The error seems related to a custom CSP you defined, either in your origin server or through Transform Rules.

Here's a list of possible troubleshooting steps:

- Make sure you disable any privacy-related browser extensions, since they're not compatible with Cloudflare challenges.
- Have you tried other browsers besides Safari? Do you get the same errors?
- Can you provide a public example page with the error you described, or can you set up a small self-contained example that shows the issue?
- Are you using other Cloudflare products that require their own [specific CSP directives](https://developers.cloudflare.com/fundamentals/reference/policies-compliances/content-security-policies/#product-requirements)?

If you keep having issues, we recommend that you [contact Cloudflare Support](https://developers.cloudflare.com/support/contacting-cloudflare-support/) or reach out to the [Cloudflare Community](https://community.cloudflare.com/) (if you have a Free plan), since this repository only deals with documentation.

**Comment by nisbet-hubbard** [comment]
Glad to report that after you raised this internally, WAF's JS Challenge can now work properly without these CSP changes.
