### ISSUE TITLE
small typo in npm command for nextjs on workers

### ISSUE THREAD

**Issue by amxv** [cloudflare/cloudflare-docs#18167]
### Existing documentation URL(s)

https://developers.cloudflare.com/workers/frameworks/framework-guides/nextjs/

### What changes are you suggesting?

the npm create command `npm create cloudflare@latest my-next-app -- --framework=next --experimental`

should be 

`npm create cloudflare@latest my-next-app --framework=next --experimental`

(removed extra dashes - the cli doesnt initialize nextjs for workers properly if included)

**Comment by amxv** [comment]
actually this typo is present in every framework page's npm command (the yarn/pnpm commands are correct)

https://developers.cloudflare.com/workers/frameworks/framework-guides/astro/
https://developers.cloudflare.com/workers/frameworks/framework-guides/solid/

**Comment by dario-piotrowicz** [comment]
Hi @amxv 👋 

Thanks for the issue 🙂 

However I don't think that the extra `--` are incorrect, I think that they are actually very necessary in npm

For example, running `npm create cloudflare@latest my-next-app -- --framework=next --experimental` does provide the expected behavior:
![Screenshot 2024-11-14 at 13 35 21](https://github.com/user-attachments/assets/0c50aa4d-c843-4cf0-89a0-f5be9a562276)

While omitting the extra `--` makes it so that `npm` ignores the `framework` and `experimental` arguments, meaning that running `npm create cloudflare@latest my-next-app --framework=next --experimental` ends up behaving like so:
![Screenshot 2024-11-14 at 13 38 45](https://github.com/user-attachments/assets/c13ac00b-ba14-40ba-b577-ff010ab77345)

(do notice how the cli is asking you what type of application you want to create instead of going straight into next.js)

So again I don't think we have a real typo/issue here, unless I am missing something? 🙂

**Comment by haleycode** [comment]
Given @dario-piotrowicz's notes, I'm going to close this out for now. @amxv if you'd like us to reopen, please go ahead and provide some more context. Thanks so much!
