### ISSUE TITLE
Incorrect file name in example guide

### ISSUE THREAD

**Issue by pksingh005** [cloudflare/cloudflare-docs#18356]
### Example URL(s)

https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/deploy-tunnels/deployment-guides/terraform/#create-a-startup-script

### Actual Behavior

The command to create the file is `touch install-tunnel.tftpl`

### Expected Behavior

The command to create the file should be 
`touch install-tunnel.tpl`

**Comment by pedrosousa** [comment]
I'd personally do it the other way around: 
* Keep the `.tftpl` extension in that command.
* Update the `GCP-config.tf` file content ([line 233](https://github.com/cloudflare/cloudflare-docs/blob/production/src/content/docs/cloudflare-one/connections/connect-networks/deploy-tunnels/deployment-guides/terraform.mdx?plain=1#L233)), since [`.tftpl` is the recommended file extension for Terraform template files](https://developer.hashicorp.com/terraform/language/functions/templatefile#:~:text=is%20the%20recommended%20naming%20pattern%20to%20use%20for%20your%20template%20files).
