### ISSUE TITLE
Next.js framework guide for worker is outdated and does not work.

### ISSUE THREAD

**Issue by t0m0120** [cloudflare/cloudflare-docs#18936]
### Existing documentation URL(s)

https://developers.cloudflare.com/workers/frameworks/framework-guides/nextjs/

### What changes are you suggesting?
The Existing Next.js apps item is out of date and does not work.
Update the content to align with the OpenNext documentation.

wrangler.toml

```diff
- main = ".worker-next/index.mjs"
+ main = ".open-next/worker.js"
name = "my-app"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
- assets = { directory = ".worker-next/assets", binding = "ASSETS" }
+ assets = { directory = ".open-next/assets", binding = "ASSETS" }
```

package.json
```diff
- "build:worker": "cloudflare",
+ "build:worker": "opennextjs-cloudflare",
"dev:worker": "wrangler dev --port 8771",
"preview:worker": "npm run build:worker && npm run dev:worker",
"deploy:worker": "npm run build:worker && wrangler deploy"
```

**Comment by dario-piotrowicz** [comment]
Hi @t0m0120, thanks a lot for flagging the outdated guide! 🫶 

We've made some breaking changes in our open-next adapter (without a major bump since it's still in beta) and forgot to update the guide here as well as the respective C3 template (which I am addressing in https://github.com/cloudflare/workers-sdk/pull/7638).

**Comment by t0m0120** [comment]
@dario-piotrowicz 
Thanks for the confirmation and correction :bow:
