### ISSUE TITLE
Help Info pleace

### ISSUE THREAD

**Issue by IvanDeFelice76** [cloudflare/cloudflare-docs#1967]
IP ??

Subnet Mask??

Gateway???

For Win.10 Pleace Info

**Comment by VARsIsYoutacRS** [comment]
I need help with all of this i cant put my things back onto mu account my g mail on my iPhone mail I'm also locked out of my cloud flair account my iPhone 7 I'm locked out of now I've been locked out of my sales force and okta.com for weeks so many things I'm locked out of because of passwords and others￼ trying to hack into it to receive my accounts and my coins￼

**Comment by KimJ15** [comment]
This issue appears to have been opened accidentally. I'm going to close it now, but feel free to open a new issue or ask any questions.
