### ISSUE TITLE
Document using Workers for a custom domain with Images

### ISSUE THREAD

**Issue by WalshyDev** [cloudflare/cloudflare-docs#2383]
### Expected Behavior
It's a very common request for people to want to serve Images on their own domain. This is on the roadmap however, there is a temporary solution with Workers. It would be nice to have this documented somewhere (either in the Images section or the Workers section) so that it can be easily linked.

Code I have shared in the past for this:
```javascript
addEventListener('fetch', (event) => {
  event.respondWith(handleRequest(event.request));
});

// You can find this in the dashboard, it should look something like this: ZWd9g1K7eljCn_KDTu_MWA
const accountHash = '';

async function handleRequest(request) {
  const { pathname } = new URL(request.url);
  // A request to something like cdn.example.com/83eb7b2-5392-4565-b69e-aff66acddd00/public
  // will fetch "https://imagedelivery.net/<accountHash>/83eb7b2-5392-4565-b69e-aff66acddd00/public"
  return fetch(`https://imagedelivery.net/${accountHash}${pathname}`, request);
}
```

It would also allow people to do something like switch the order of variant and account hash.

---

Personally, I think this can fit in either Images or Workers however I'd understand if the Images team would prefer not having this workaround there currently considering it's on the roadmap.

cc: @Albertozhao @signalnerve - do you think it could fit in the Workers examples/tutorials section if it shouldn't go in Images?

**Comment by KianNH** [comment]
Is this still something that we're looking to document? You can serve Images under your own domain since it exists under `/cdn-cgi/`

`https://images.kian.org.uk/cdn-cgi/imagedelivery/kdRbTDgaPUHq8PGsHZ1fKA/4d263d6d-cdb6-4781-fe91-a4a45ee1bc00/public` => `https://imagedelivery.net/kdRbTDgaPUHq8PGsHZ1fKA/4d263d6d-cdb6-4781-fe91-a4a45ee1bc00/public`

**Comment by deadlypants1973** [comment]
> Is this still something that we're looking to document? You can serve Images under your own domain since it exists under `/cdn-cgi/`
> 
> `https://images.kian.org.uk/cdn-cgi/imagedelivery/kdRbTDgaPUHq8PGsHZ1fKA/4d263d6d-cdb6-4781-fe91-a4a45ee1bc00/public` => `https://imagedelivery.net/kdRbTDgaPUHq8PGsHZ1fKA/4d263d6d-cdb6-4781-fe91-a4a45ee1bc00/public`

yes this is definitely still something we need to document

**Comment by kristianfreeman** [comment]
> Is this still something that we're looking to document? You can serve Images under your own domain since it exists under `/cdn-cgi/`
> 
> `https://images.kian.org.uk/cdn-cgi/imagedelivery/kdRbTDgaPUHq8PGsHZ1fKA/4d263d6d-cdb6-4781-fe91-a4a45ee1bc00/public` => `https://imagedelivery.net/kdRbTDgaPUHq8PGsHZ1fKA/4d263d6d-cdb6-4781-fe91-a4a45ee1bc00/public`

wow fascinating! to be clear, you can do this w/o a worker deployed? TIL!

**Comment by KianNH** [comment]
If you're happy with that URL format haha, yeah - you can also apply custom caching to it but it's not the nicest.

Transform rules for response headers can be applied to `/cdn-cgi/imagedelivery/` so you can have a year or whatever else instead of the default 4 hours.

https://community.cloudflare.com/t/cloudflair-image-ttl-time/390927/4?u=kiannh
