### ISSUE TITLE
Configuration file reference missing `protocol` key

### ISSUE THREAD

**Issue by velocity23** [cloudflare/cloudflare-docs#2540]
### Expected Behavior
The new `protocol` key announced yesterday is not yet documented in the configuration file reference for `cloudflared`. I had to dig through the `cloudflared` changelog to find that I can indeed use it in the configuration file and not just in the CLI.

### Actual Behavior
It is not documented

### Section that requires update
"Keys and values" section
https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/configuration/configuration-file

### Additional information
N/A

**Comment by KianNH** [comment]
Looks like `auto` (aka `AutoSelectFlag`), `h2mux`, `http2` and `quic` are supported - from my recollection, this seems accurate.

```go
func (p Protocol) String() string {
	switch p {
	case H2mux:
		return "h2mux"
	case HTTP2, HTTP2Warp:
		return "http2"
	case QUIC, QUICWarp:
		return "quic"
	default:
		return fmt.Sprintf("unknown protocol")
	}
}
```

Should be easy enough to document the `protocol` key & list the above as valid options, but I'm not massively familiar with the actual explanation around *what* or *why* you would use one protocol over the other.

**Comment by KianNH** [comment]
Turns out right above where I was in the codebase, it's documented.

`AvailableProtocolFlagMessage = "Available protocols: 'auto' - automatically chooses the best protocol over time (the default; and also the recommended one); 'quic' - based on QUIC, relying on UDP egress to Cloudflare edge; 'http2' - using Go's HTTP2 library, relying on TCP egress to Cloudflare edge; 'h2mux' - Cloudflare's implementation of HTTP/2, deprecated"`

Will make a PR tomorrow.

**Comment by ranbel** [comment]
#5553
