### ISSUE TITLE
Query on Documentation: Create Rate Limiting rules via API 

### ISSUE THREAD

**Issue by spongenee** [cloudflare/cloudflare-docs#2546]
Hi Support,

Thank you for your quick response last time. 

I was checking on the CloudFlare API documentation regarding rate limiting rules and I wonder the difference between 
`https://api.cloudflare.com/client/v4/zones/{zone-id}/rulesets/phases/http_ratelimit/entrypoint` and
`https://api.cloudflare.com/client/v4/zones/023e105f4ecef8ad9ca31a8372d0c353/rate_limits`

The list of rate limiting rules I get from `https://api.cloudflare.com/client/v4/zones/$zone_id/rate_limits` shows the custom rules under Website > Firewall > Tools > Rate Limiting

I notice [CloudFlare Docs](https://developers.cloudflare.com/waf/custom-rules/rate-limiting) mentions the rate limiting rules is limited to beta users. I wonder if the two urls work the same and if [this explanation](https://developers.cloudflare.com/waf/custom-rules/rate-limiting/request-rate) applies for the rate limits for a zone as well. 

Thank you in advance.

**Comment by spongenee** [comment]
On the same topic, when I try the curl example of creating a rate limit for a zone in the [documentation](https://api.cloudflare.com/#rate-limits-for-a-zone-list-rate-limits), I get the following error, but the documentation does not explain the parameters to a sufficient degree.
```
{
  "result": null,
  "success": false,
  "errors": [
    {
      "message": "ratelimit.api.validation_error:timeout and response are not allowed for action(challenge)"
    }
  ],
  "messages": []
}
```

**Comment by pedrosousa** [comment]
Hi @spongenee 

Thank you for your feedback.

The Rate Limiting rules described in Cloudflare Developers documentation are based on the [Ruleset Engine](https://developers.cloudflare.com/ruleset-engine/). The first API endpoint you mentioned is related to this recent feature with limited availability:
`https://api.cloudflare.com/client/v4/zones/<zone-id>/rulesets/phases/http_ratelimit/entrypoint`

There's a separate Cloudflare Rate Limiting product, available at Firewall > Tools > Rate Limiting, that refers to a different implementation of rate limiting that is still not based on the Ruleset Engine. The other API endpoint you mentioned is related to this product:
`https://api.cloudflare.com/client/v4/zones/<zone-id>/rate_limits`
The documentation for Cloudflare Rate Limiting is [available in the Support KB](https://support.cloudflare.com/hc/en-us/articles/115001635128-Configuring-Cloudflare-Rate-Limiting).

The list of rules between both implementations is separate, since they are in fact different products with different availability.

We'll try to make this difference more clear in the documentation.

**Comment by pedrosousa** [comment]
Regarding your second question, The API documentation includes some relevant information for your specific case in the [Object definition](https://api.cloudflare.com/#rate-limits-for-a-zone-properties) section in the "Constraints" column:

> * `timeout` — If `mode` is `challenge` or `js_challenge` then the Zone Challenge Passage time is used and this value should not be supplied.
> * `response` — If `mode` is `challenge` or `js_challenge` then the Zone challenge pages are used and this object should not be supplied.
