### ISSUE TITLE
pages: build configuration: list latest versions available

### ISSUE THREAD

**Issue by benblazak** [cloudflare/cloudflare-docs#2746]
### Expected Behavior
The Cloudflare pages build configuration page should ideally list the range of versions available for various software, or give an easy way to find them.

### Actual Behavior
Only the default versions are listed.

Also, in the case of Python, the listed version (2.7) is EOL.

### Section that requires update
https://github.com/cloudflare/cloudflare-docs/blob/production/products/pages/src/content/platform/build-configuration.md

**Comment by michaelr0** [comment]
Agreed, I got excited when I seen PHP as an option, as that would allow me to use Statamic's SSG directly during the build/deployment step on Pages. However my project uses PHP 8.0.x and this version of PHP is not available, however 8.0.0 was released as a stable release on the 26th of Nov 2020 and 8.1 just recently came out.

I'm unsure what versions are actually supported, but 5.6, 7.0, 7.1, 7.2 have since past EOL and 7.3 is due to EOL in 5 days.

**Comment by Stanzilla** [comment]
They also point to the (outdated) Netlify docs. Pages is using the old Netlify images which do not have current versions of many things, for example Cloudflare Pages does not support Python 3.8 or newer.

**Comment by Stanzilla** [comment]
Any updates? It's a bit embarrassing that Cloudflare does not act on this. 3.8 came out in 2019..

**Comment by jkup** [comment]
Hey all! Sorry for the delay in updating this issue!

@benblazak as for listing all the supported versions, this is a feature request I've seen before in our Discord and I think it would be great to have! I talked with the eng team and they agreed so I made an internal ticket for them to add support for this. I'm going to close out this issue but it's currently waiting on them to prioritize. I linked it to both the Discord threads and this issue!

@Stanzilla I totally understand this frustration. We don't currently have Python 3.8, but we're hoping to add support for this and other languages and versions later this year!

Thanks all!
