### ISSUE TITLE
Defect

### ISSUE THREAD

**Issue by MikeMalter** [cloudflare/cloudflare-docs#2843]
I get this error when applying this firewall rule. 

**Filter parsing error (1:181): http.request.method eq "POST" and http.request.uri.path matches "(comment|conversation|event poll)create" and not http.cookie matches "auth_session=[0-9a-zA-Z]32-[0-9]10-[0-9a-z]6"' ^ unrecognised input**

**Comment by pedrosousa** [comment]
Hi @MikeMalter 

I believe you have an extra single quote at the end of your filter expression (after `6"`).

If this doesn't solve your problem, please reach out to the [Cloudflare Community](https://community.cloudflare.com/) with your specific question, since we only handle documentation issues in this repository. Thanks!
