### ISSUE TITLE
Having root and output set with Exit 0 command causing builds to fail

### ISSUE THREAD

**Issue by ghost** [cloudflare/cloudflare-docs#3148]
### Expected Behavior
When `exit 0` is set in the **Build Command** field and no prebuild environment is chosen, only one field should be specified (output or root?).

### Actual Behavior
Specifying both the root directory and output directory with the `exit 0` command causes builds to fail.

### Section that requires update
[Provide a link to the page that needs an update and be specific about which section requires the update.](https://developers.cloudflare.com/pages/framework-guides/deploy-anything#deploying-with-cloudflare-pages)

### Additional information
A simple clarification in the docs about this issue could be very useful, especially for beginners/non-devs.

**Comment by WalshyDev** [comment]
Both fields can be set fine with `exit 0` or any command. What's the error you're getting?

(also, I'd recommend getting support on Discord - https://workers.community)

**Comment by ghost** [comment]
> Both fields can be set fine with `exit 0` or any command. What's the error you're getting?
> 
> (also, I'd recommend getting support on Discord - https://workers.community)

[I just came from there](https://discord.com/channels/595317990191398933/789155108529111069/931311033795104790)

**Comment by WalshyDev** [comment]
Ah, I see. Greg was referring to the fact that you should set your output or root since you're attempting to point them both to the same location. Right now your output folder would be `/public/public` not `/public` hence why you would only need to set one of them :)

Clarification on that could be improved in the docs. However, it isn't related to having both directories and a command. Hopefully, this clears it up!

**Comment by lukeed** [comment]
Closing as this was about the relationship between the root & output directories, not about `exit 0` or any build command.
