### ISSUE TITLE
Cloudflare Workers - Direct Creator Upload API call

### ISSUE THREAD

**Issue by danboyle8637** [cloudflare/cloudflare-docs#3722]
### Expected Behavior

These docs say to use a Bearer token.

[Direct Creator Upload on Cloudflare Docs](https://github.com/cloudflare/cloudflare-docs/blob/production/content/images/cloudflare-images/upload-images/direct-creator-upload.md)

These docs say to use X-Auth headers...

[Direct Creator Upload on Cloudflare API Docs](https://api.cloudflare.com/#cloudflare-images-create-authenticated-direct-upload-url-v2)

### Actual Behavior

For testing I am using my global API key.

In Postman I get authentication failed when trying to use the Bearer token.

But I can get a successful response when...

- I use the X-Auth headers
- Set content type of application json
- And send form-data rather than json body.

In my Worker... dev mode... have not tried in a production Worker.

When I...

- Set X-Auth headers
- Set form-data

I get a 200 response but no data in the response object. It's empty.

I do get an authentication failed when I use the Bear token.

### Section that requires update

I'm not sure what needs updating because there are two different ways and none seem to work as stated.

**Comment by xjewer** [comment]
@danboyle8637 there are 3 separate questions here:

1. https://api.cloudflare.com/#getting-started-requests access key and access token are different, but you can use any of them to authenticate. Access key is used with X-Auth header, where is access token works with Bearer authentication
2. > Set content type of application json 

here is no need to set content/type to `application/json` for multipart upload, it will be disregarded, we're yet to clean the docs to remove this ambiguity.
3. > I get a 200 response but no data in the response object. It's empty.

note that with direct upload, request to API creates a special URL which should be later used to upload an image data itself. Requesting such image record from API will tell that record in in draft state, e.g.:

```json
{
  "result": {
    "id": "2cdc28f0-017a-49c4-9ed7-87056c83901",
    "metadata": {
      "key": "value":
    },
    "uploaded": "2022-01-31T16:39:28.458Z",
    "requiredSignedURLs": true,
    "variants": [
      "https://imagedelivery.net/Vi7wi5KSItxGFsWRG2Us6Q/2cdc28f0-017a-49c4-9ed7-87056c83901/public",
      "https://imagedelivery.net/Vi7wi5KSItxGFsWRG2Us6Q/2cdc28f0-017a-49c4-9ed7-87056c83901/thumbnail" 
    ],
    "draft": true
  },
  "success": true,
  "errors": [],
  "messages": []
}
```

variants link if requested will return 404 http status code, because there is no image data yet, but once a creator (suppose to be a user of your application) uploads an image, it will be available by its id.
