### ISSUE TITLE
wp2static is no longer available

### ISSUE THREAD

**Issue by volkanger** [cloudflare/cloudflare-docs#407]
As of Aug 10, the plugin is no more available for download which is linked from this tutorial: https://github.com/cloudflare/cloudflare-docs/tree/production/products/workers/src/content/tutorials/deploy-a-static-wordpress-site

**Comment by plantoeat** [comment]
This may be a good alternative. https://wordpress.org/plugins/simply-static/

**Comment by mrwweb** [comment]
@volkanger @deadlypants1973 While it's true that WP2Static is no longer in the official WordPress.org plugin repository, it appears to still be [actively in development on Github](https://github.com/leonstafford/wp2static) and has a [stand-alone website](https://wp2static.com) with a [Cloudflare Workers Add-on](https://wp2static.com/addons/cloudflare-workers/).

Taken together, I don't see any evidence that this plugin has been abandoned. Instead, the Cloudflare document needs to be updated to install the plugin from Github rather than the WP repo.

@leonstafford is the primary developer and may want to be aware of this issue.

**Comment by leonstafford** [comment]
Thanks @mrwweb! 

Yes, still very much in development, including the Workers addon.

**Comment by kristianfreeman** [comment]
@leonstafford hey leon! would you be interested in helping us update this tutorial with the new installation method via github?

alternatively, would love to hear if you've been working on anything with cf pages :) since we wrote this tutorial, we've released pages as a better/more-managed solutions to workers sites, it would be neat to get a pages-centric tutorial up that uses wp2static, if you're interested!

**Comment by leonstafford** [comment]
Hey @signalnerve! Definitely! Pages flow should be easier, I'll try to dive into that soon and add instructions re GH usage in the meantime.
