### ISSUE TITLE
waf rule blocked some ip which is not in the rule

### ISSUE THREAD

**Issue by Scumwong** [cloudflare/cloudflare-docs#4152]
I created a waf rule to block china ip address and the rule run normal until i found that an address from singapore 103.254.155.225 was blocked by the rule . I am confused about this and i want to know why . can anyone explain this?Thanks very much.

**Comment by pedrosousa** [comment]
Hi @Scumwong 
We only deal with documentation issues in this repository, but I'll try to provide some additional information.

Geolocation information, including country information based on the IP address, is provided by a third party. Depending on how up to date their information is, you may get an occasional incorrect identification.

For example, using the IP address you provided, MaxMind states that its associated country is China:
https://www.maxmind.com/en/geoip2-precision-demo?ip_address=103.254.155.225

Other geolocation providers return China or Singapore for the same IP address:
https://www.iplocation.net/ip-lookup (you must enter the IP address in the IP Location Finder search box)

You may report incorrect information to these data providers so that they can fix it in their geolocation databases.

**Comment by Scumwong** [comment]
> Hi @Scumwong We only deal with documentation issues in this repository, but I'll try to provide some additional information.
> 
> Geolocation information, including country information based on the IP address, is provided by a third party. Depending on how up to date their information is, you may get an occasional incorrect identification.
> 
> For example, using the IP address you provided, MaxMind states that its associated country is China: https://www.maxmind.com/en/geoip2-precision-demo?ip_address=103.254.155.225
> 
> Other geolocation providers return China or Singapore for the same IP address: https://www.iplocation.net/ip-lookup (you must enter the IP address in the IP Location Finder search box)
> 
> You may report incorrect information to these data providers so that they can fix it in their geolocation databases.

ok i know ...Thank you so much
