### ISSUE TITLE
Zero Trust: documentation missing for "Private network" app type

### ISSUE THREAD

**Issue by matt-matt-tmatt** [cloudflare/cloudflare-docs#4373]
### Product

Zero Trust Access

### Subject Matter

There's an app type on the admin panel's GUI called "Private network" which is not documented

### Content Location

On the Applications page (link below)

#### For example, should this be a new document, a new section within an existing document, or a call-out within a section?

New section under "Applications"

#### Please provide any URLs to existing documents.

https://github.com/cloudflare/cloudflare-docs/blob/production/content/cloudflare-one/applications/_index.md

### Any other details or screenshots that may be relevant.

![image](https://user-images.githubusercontent.com/74046491/167779954-0e5a90e0-2f99-4282-8e84-d1b90a5a31c1.png)

**Comment by ranbel** [comment]
Hi, thanks for the feedback. The private network documentation is currently located under "Connections": https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/private-net/
However, we're working on refactoring the "Connections" docs so that things will be easier to find.  If you have other suggestions then please let us know!
