### ISSUE TITLE
clarify x-forwarded-for manipulation

### ISSUE THREAD

**Issue by lobeck** [cloudflare/cloudflare-docs#4741]
### Which Cloudflare product does this pertain to?

Rules

### Existing documentation URL(s)

https://developers.cloudflare.com/rules/transform/request-header-modification/

### Section that requires update

#important-remarks

### What needs to change?

The page states, that X-Forwarded-For and some other headers can not be manipulated. However it is possible to drop the header on incoming requests and it will be added again by the underlaying fetch request to the origin.

From a security perspective, this is a helpful behaviour, as it allows you to drop any incoming header (which can be manipulated) and have it replaced by a trustworthy value in the origin request.

### How should it change?

It should be clarified here, if it's expected, that the headers can be dropped or if this is a bug and no manipulation at all should be possible.

So either add a statement, that removing these headers is supported and they will be added back or if no manipulation at all is allowed.

**Comment by pedrosousa** [comment]
Hi @lobeck 
You cannot change the value of the `X-Forwarded-For` header (and similar headers), but you should be able to remove it using a Transform Rule (or a Managed Transform). There's currently an issue where the header eventually gets re-added when you remove it, but the intended behavior is that you can remove the header but not modify its value, and such header will not be re-added later in the request handling process before it gets to the origin server.

As soon as this issue is solved, I'll review that sentence in the documentation so that it's clear that you can remove these headers, but you cannot modify their values.

**Comment by lobeck** [comment]
> There's currently an issue where the header eventually gets re-added when you remove it, but the intended behavior is that you can remove the header but not modify its value, and such header will not be re-added later in the request handling process before it gets to the origin server.

Oh, that's actually good to know, as we're relying on that behaviour.

That behaviour is also somewhat logical, as the header will be removed when a request is received and then re-added internally. If you want to really remove these headers, there is still the managed transformation "Remove visitor IP headers" which would strip it.

**Comment by pedrosousa** [comment]
I'm not sure if my answer was clear.
The behavior of Transform Rules and Managed Transforms will be the exactly the same in this regard: removed headers will **not** be re-added later, as soon as the issue I pointed out is solved.

**Comment by lobeck** [comment]
I understood your answer. I was saying, that in my opinion, this bug shouldn't be fixed :D
