### ISSUE TITLE
Note breaking errors with extraneous headers on caption upload

### ISSUE THREAD

**Issue by HBBrenum** [cloudflare/cloudflare-docs#4915]
### Which Cloudflare product does this pertain to?

Stream

### Existing documentation URL(s)

https://developers.cloudflare.com/stream/uploading-videos/adding-captions/

### Section that requires update

Add or Modify a Caption

### What needs to change?

The curl example provided only calls out the explicit authorization header, but curl passes implicit headers with the `-F` option. Including those headers explicitly when using other methods than curl to attempt to upload captions (for example the requests library in python) will, at best, throw an HTTP 400 and an error code 10004 Decoding Error in the response. Code 10004 is not particularly specific, nor does searching for it turn up many helpful support results for captions specifically (most results from the CF forums or elsewhere are in relation to video uploads).

### How should it change?

Clarifying that the authorization headers are the _only_ headers that should be passed, regardless of any implicit headers that curl sends and/or providing resources for the CF error codes that users might encounter would reduce frustration.

**Comment by dcpena** [comment]
Hi @HBBrenum! Thanks for opening the issue and for the level of detail you provided. The docs will be updated soon, and this issue will be updated when that happens. Thanks again!

**Comment by renandincer** [comment]
Hey @HBBrenum! Thank you for the patience as I was just able to find time to respond. I work on the Stream team and trying to understand your report better to either fix our API or make sure we update our docs to clarify what we might have miscommunicated.

When I make a request to the captions API with extra headers, the API works as expected. Below I've added `coconut: mango` as a extra header (note that I've edited the verbose output from cURL for clarity but retained every header sent and received).

```
curl -X PUT 'https://api.cloudflare.com/client/v4/accounts/a67e14daa5f8dceeb91fe5449ba496eb/stream/644822f93dcddab3e9441587d184ca2f/captions/tr' -H 'Authorization:Bearer $KEY' -H 'coconut: mango' -F 'file=@webvtt.vtt' -v   

> PUT /client/v4/accounts/a67e14daa5f8dceeb91fe5449ba496eb/stream/644822f93dcddab3e9441587d184ca2f/captions/tr HTTP/2
> Host: api.cloudflare.com
> user-agent: curl/7.81.0
> accept: */*
> authorization:Bearer $KEY
> coconut: mango
> content-length: 341
> content-type: multipart/form-data; boundary=------------------------79e17072d3916653
> 

< HTTP/2 200 
< date: Fri, 01 Jul 2022 04:57:25 GMT
< content-type: application/json; charset=UTF-8
< cf-ray: 723c8f88cb4b97f3-SJC
< set-cookie: __cflb=0H28vgHxwvgAQtjUGU4vq74ZFe3sNVUZaMyNVGZn96V; SameSite=Lax; path=/; expires=Fri, 01-Jul-22 07:27:26 GMT; HttpOnly
< vary: Accept-Encoding
< cf-cache-status: DYNAMIC
< expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< x-envoy-upstream-service-time: 357
< set-cookie: __cfruid=ea7468a07291429f358ddc25c2555d0788f84542-1656651445; path=/; domain=.api.cloudflare.com; HttpOnly; Secure; SameSite=None
< server: cloudflare
< 
{
  "result": {
    "language": "tr",
    "label": "Türkçe"
  },
  "success": true,
  "errors": [],
  "messages": []
}

```
As you can see, adding the header `coconut` is fine. 

However, if I try to set content-type, it is not:

```
curl -X PUT 'https://api.cloudflare.com/client/v4/accounts/a67e14daa5f8dceeb91fe5449ba496eb/stream/644822f93dcddab3e9441587d184ca2f/captions/tr' -H 'Authorization:Bearer $KEY' -H 'Content-Type: text/vtt' -F 'file=@webvtt.vtt' -v

> PUT /client/v4/accounts/a67e14daa5f8dceeb91fe5449ba496eb/stream/644822f93dcddab3e9441587d184ca2f/captions/tr HTTP/2
> Host: api.cloudflare.com
> user-agent: curl/7.81.0
> accept: */*
> authorization:Bearer $KEY
> content-length: 342
> content-type: text/vtt; boundary=------------------------795314ec39dbb78e
> 

< HTTP/2 400 
< date: Fri, 01 Jul 2022 05:50:50 GMT
< content-type: application/json; charset=UTF-8
< cf-ray: 723cddce2dd2643b-SJC
< set-cookie: __cflb=0H28vgHxwvgAQtjUGU4vq74ZFe3sNVUZbP8MasUPhY1; SameSite=Lax; path=/; expires=Fri, 01-Jul-22 08:20:51 GMT; HttpOnly
< vary: Accept-Encoding
< cf-cache-status: DYNAMIC
< expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< x-envoy-upstream-service-time: 8
< set-cookie: __cfruid=836842155ee90a5c4e44c653c70c9cbb047c7232-1656654650; path=/; domain=.api.cloudflare.com; HttpOnly; Secure; SameSite=None
< server: cloudflare
< 
{
  "result": null,
  "success": false,
  "errors": [
    {
      "code": 10004,
      "message": "Decoding Error"
    }
  ],
  "messages": null
}

```

This is because this endpoint expects data to be uploaded in form of [`multipart/form-data`](https://everything.curl.dev/http/multipart) ([RFC7578](https://datatracker.ietf.org/doc/html/rfc7578)). By setting the `content-type` header, the request is no longer a valid multipart upload, which causes the Stream API to fail at decoding. 

You mentioned that you use the python requests library to interact with the Stream API. Though I don't claim to be expert in Python, I've looked at the `requests` library documentation and found a multipart upload example: https://requests.readthedocs.io/en/latest/user/quickstart/#post-a-multipart-encoded-file. I would suggest to use a library to construct a multipart upload.

Going forward, one solution I'm bringing is to clarify this error condition make make it clear the type of upload we expect when we fail to parse. I have a pull request internally that makes an attempt to clarify when this error case it hit:
```
{
  "result": null,
  "success": false,
  "errors": [
    {
      "code": 10004,
      "message": "Decoding Error"
    }
  ],
  "messages": [
    {
      "code": 10004,
      "message": "Could not parse the multipart form upload. Please verify that this is a valid multipart upload with a key named 'file'."
    }
  ]
}
```

Do you think this would make it more clear and would have prevented this issue? Please feel free to correct me if I'm misunderstanding your report. I will comment again when my PR gets deployed into production.

**Comment by HBBrenum** [comment]
Hi @renandincer thanks for the response! The trouble I ran into was with the `content-type` header. I thought that I was failing to upload with the `requests` library even when specifying `multipart/form-data` as the type, but I can't reproduce that result now.

I suppose the easiest resolution from my perspective, and the thing that, aside from the expanded error message, would have saved me the most time, is if the example curl command in the docs specifically called out the `content-type: multipart/form-data` header.

**Comment by renandincer** [comment]
Hey! Mini update here, we've deployed the change I mentioned above. You should get a better API response if this happens again.

You're right, I agree with you that we should call out the multipart upload in the docs, the `-F` in the curl does this but it's very implicit.

**Comment by dcpena** [comment]
Closing now that this is fixed.
