### ISSUE TITLE
How to upload more than 5gb using r2

### ISSUE THREAD

**Issue by Wolfsil** [cloudflare/cloudflare-docs#5148]
### Which Cloudflare product(s) does this pertain to?

R2

### Subject Matter

How to upload more than 5gb using r2

### Content Location

Hello, I wonder how to upload more than 5gb files using r2. Is it impossible to upload using "multi-part upload", like s3?

**Comment by KianNH** [comment]
The S3 API of R2 supports multipart uploads just fine

**Comment by Wolfsil** [comment]
Thank you very much for your quick response. If you don't mind, can I ask you this too?
Even in the presented url?

**Comment by KianNH** [comment]
It'll act the same way as pretty much any other S3 compatible API - you can use the AWS SDK's like `aws-sdk-js` or utilities like `rclone`

https://developers.cloudflare.com/r2/examples/

`rclone` or the `aws` CLI are likely easier since the SDKs would require you to construct all of the operations yourself.

**Comment by KianNH** [comment]
@deadlypants1973 imho closed by https://github.com/cloudflare/cloudflare-docs/pull/5014 & https://github.com/cloudflare/cloudflare-docs/pull/5168
