### ISSUE TITLE
Add `environment` to Durable Object `wrangler.toml` definition

### ISSUE THREAD

**Issue by GregBrimble** [cloudflare/cloudflare-docs#5383]
### Which Cloudflare product does this pertain to?

Workers

### Existing documentation URL(s)

https://developers.cloudflare.com/workers/wrangler/configuration/

### Section that requires update

Example configuration

### What needs to change?

Add `environment` option to the `durable_objects` section

### How should it change?

When configuring a Durable Object binding to an external script (using `script_name`), you're able to also specify an `environment`. The example should probably be updated to demonstrate that.

### Additional information

https://github.com/cloudflare/wrangler2/pull/1019

**Comment by KianNH** [comment]
FYI, the `environment` option is documented in the refactor: https://github.com/cloudflare/cloudflare-docs/pull/5150

From the looks of https://github.com/cloudflare/wrangler2/pull/1019, it's exclusive to Service Environments at the moment so I suppose there's no rush to get it in since Service Environments aren't currently enabled - but if that's not the case then I'm happy to throw it into the existing docs.

**Comment by deadlypants1973** [comment]
> FYI, the `environment` option is documented in the refactor: #5150
> 
> From the looks of [cloudflare/wrangler2#1019](https://github.com/cloudflare/wrangler2/pull/1019), it's exclusive to Service Environments at the moment so I suppose there's no rush to get it in since Service Environments aren't currently enabled - but if that's not the case then I'm happy to throw it into the existing docs.

Does #5150 close this issue?

**Comment by GregBrimble** [comment]
Looks like it would, yeah 👍
