### ISSUE TITLE
Update cache.match documentation

### ISSUE THREAD

**Issue by lrapoport-cf** [cloudflare/cloudflare-docs#6097]
### Which Cloudflare product does this pertain to?

Workers

### Existing documentation URL(s)

https://developers.cloudflare.com/workers/runtime-apis/cache/#match

### Section that requires update

`cache.match`: https://developers.cloudflare.com/workers/runtime-apis/cache/#match

### What needs to change?

according to https://developer.mozilla.org/en-US/docs/Web/API/Cache/match, cache.match documentation should be updated to reflect that:
- accepts URL/string in addition to a Request
- result should be Promise<Response | undefined>

### How should it change?

according to https://developer.mozilla.org/en-US/docs/Web/API/Cache/match, cache.match documentation should be updated to reflect that:
- accepts URL/string in addition to a Request
- result should be Promise<Response | undefined>

**Comment by helloimalastair** [comment]
@lrapoport-cf, I think this section of MDN is kind of unclear. While
> The [Request](https://developer.mozilla.org/en-US/docs/Web/API/Request) for which you are attempting to find responses in the [Cache](https://developer.mozilla.org/en-US/docs/Web/API/Cache). This can be a [Request](https://developer.mozilla.org/en-US/docs/Web/API/Request) object or a URL.

does make it seem like it would take a URL; Since it isn't linking to [URL](https://developer.mozilla.org/en-US/docs/Web/API/URL/URL) makes me think it is only *supposed* to take a URL in the form of a `string`. In any case, [`@cloudflare/workers-types`](https://cdn.jsdelivr.net/npm/@cloudflare/workers-types/index.d.ts) seems to show `cache.match` only accepting a URL in the form of a string, which is documented: 
![image](https://user-images.githubusercontent.com/37487746/197967795-0fb14406-036d-4f39-ba41-a63914166120.png)

As for the return-type of `cache.match` not having `undefined`, I've addressed that in #6423.
