### ISSUE TITLE
Misleading legal disclosures, and missing jurisdictions in multiple places

### ISSUE THREAD

**Issue by gitcnd** [cloudflare/cloudflare-docs#6165]
### Which Cloudflare product does this pertain to?

1.1.1.1

### Existing documentation URL(s)

https://developers.cloudflare.com/1.1.1.1/privacy/public-dns-resolver/

https://www.cloudflare.com/transparency/

### Section that requires update

Wording around disclosures and government 

### What needs to change?

This URL: https://developers.cloudflare.com/1.1.1.1/privacy/public-dns-resolver/
fails to disclose the jurisdiction that apply to statements it makes, particularly those relating to the term "legal".

e.g. "We also commit to documenting any government request to block access in our semi-annual transparency report, unless legally prohibited from doing so."

If, for example, you're based in the USA, and you get an access demand from Australia along with a gag order, Australian law does NOT APPLY in the USA, so such a request would NOT "legally prevent" you from disclosing it.

Thus, it is important that your policy informs users what jurisdiction you are in, so we can understand the global extent of any gag orders you get.

Also - see below about your "Things we have never done" misleading statements (if they're not yet misleading, as soon as you're gagged and unhallowed to remove them, they then become so)

### How should it change?

"Canaries" are illegal in many countries - you can go to Jail for a VERY long time if you take any action that reveals a gag order (e.g. saying you got one is illegal obviously, and equally-so nowadays is *stopping* the saying of a statement that you did not get one).

You need to CLEARLY declare what exact STATE and FEDERAL jurisdiction applies to you, so everyone can understand the truth of your statements, and if you're in a place (e.g. Australia) with serious criminal consequences for gag-order/canary violations, you need to spell those out along with your statements, so we know whether or not it's even possible for them to be true, and you need to do this BEFORE you get a gag order, because afterwards is criminal.

I'm referring to these, which (if you got a gar order) would never be allowed to change or remove, even when they're no longer true:-

SOME THINGS WE HAVE NEVER DONE
Cloudflare has never turned over our encryption or authentication keys or our customers' encryption or authentication keys to anyone.

Cloudflare has never installed any law enforcement software or equipment anywhere on our network.

Cloudflare has never provided any law enforcement organization a feed of our customers' content transiting our network.

Cloudflare has never modified customer content at the request of law enforcement or another third party.

Cloudflare has never modified the intended destination of DNS responses at the request of law enforcement or another third party.

Cloudflare has never weakened, compromised, or subverted any of its encryption at the request of law enforcement or another third party.

### Additional information

Someone fraudulently closed my earlier similar report: https://github.com/cloudflare/cloudflare-docs/issues/4350

This is a SERIOUS legal request.  Please fix it properly using lawyers, instead of just closing it and spitting in the face of everyone you're pretending to be transparent with.

**Comment by elithrar** [comment]
Our public position on this is detailed in our transparency report: https://cf-assets.www.cloudflare.com/slt3lc6tev37/7JOzEbaUD1HVuYjqm1Ymc7/a3d7c3b1a5217a008b3d24a45d55f661/Transparency-Report-2H_2021.pdf — I am linking this again with intent, through discussion with our Legal & Policy teams.

> Cloudflare has also received a small number of legal
requests related to blocking or filtering content
through the 1.1.1.1 Public DNS Resolver. Because
such a block would apply globally to all users of
the resolver, regardless of where they are located,
it would affect end users outside of the blocking
government’s jurisdiction. We therefore evaluate
any government requests or court orders to block
content through a globally available public
recursive resolver as requests or orders to block
content globally.
> Given the broad extraterritorial effect, as well as the
different global approaches to DNS-based blocking,
Cloudflare has pursued legal remedies before
complying with requests to block access to
domains or content through the 1.1.1.1 Public
DNS Resolver or identified alternate mechanisms
to comply with relevant court orders. To date,
Cloudflare has not blocked content through the 1.1.1.1
Public DNS Resolver.
