### ISSUE TITLE
Content overflow on an R2 documentation page

### ISSUE THREAD

**Issue by sdnts** [cloudflare/cloudflare-docs#6205]
### Example URL(s)

https://developers.cloudflare.com/r2/data-access/s3-api/api/

### Actual Behavior

I see the second table on the page overflowing into the right sidebar:

<img width="1245" alt="Screenshot 2022-10-10 at 15 36 24" src="https://user-images.githubusercontent.com/7689783/194878916-18715aff-714c-4039-a89a-e7dba84be9cd.png">

This happens on all browsers

### Expected Behavior

No overflow

**Comment by Frederik-Baetens** [comment]
I talked with kate about this a while back, and she said she preferred this over requiring longer headers to wrap, which would look disorienting. Instead of doing that, you might be able to solve this by squishing the floating navigation element further to the right? 

Or perhaps there's a way to reduce the whitespace required to the right of the header before wrapping? The floating navigation never actually overlaps with the headers, so that might be a possible approach?

**Comment by Frederik-Baetens** [comment]
Made a PR to fix this since I already looked at the source for that page when looking into that a while ago, so it was very quick to do so :) .
