### ISSUE TITLE
Please provide support for pi-hole

### ISSUE THREAD

**Issue by mushu999** [cloudflare/cloudflare-docs#647]
Need documentation on how to enable this on a pi-hole installation for home networks. It is possible that the pi-hole folks need to add supporting code to the software for compatibility, but this should still be a document from Cloudflare.

**Comment by TownLake** [comment]
Hi! Could you help us understand what use case you'd like to see documented? Pi-hole [provides documentation](https://docs.pi-hole.net/guides/dns/upstream-dns-providers/#cloudflare-dns) for using Cloudflare's resolver, but are there specific areas you'd like to see elaborated?

**Comment by taymarjor** [comment]
Hello! I have to be honest, I am not super familiar with all of these platforms, but am starting to think I did something wrong and I caused all this confusion. Please offer any advisement in going forward. The only thing I do know is that I was used the accounts to get into a server. I’m worried I caused an inconvenience due to my lack of knowledge and I wanted to apologize. If you don’t know what it is, then It’s probably a scam because I don’t either. I’m so sorry! I don’t know if I subscribed to an entire chain or my specific case, so I never knew if I should say anything or what was honestly happening. My apologies!!!!!!!!!! Sent from Mail for Windows 10 From: Samuel RheaSent: Monday, March 15, 2021 4:09 PMTo: cloudflare/cloudflare-docsCc: SubscribedSubject: Re: [cloudflare/cloudflare-docs] Please provide support for pi-hole (#647) Hi! Could you help us understand what use case you'd like to see documented? Pi-hole provides documentation for using Cloudflare's resolver, but are there specific areas you'd like to see elaborated?—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by KimJ15** [comment]
Closing this ticket due to inactivity.
