### ISSUE TITLE
Consider replacing markdown links with `{{< ref >}}`

### ISSUE THREAD

**Issue by jbergstroem** [cloudflare/cloudflare-docs#6670]
### Example URL(s)

Any link on the site that references other parts seems to use plain markdown links. These can be replaced with Hugo's [`ref`](https://gohugo.io/content-management/cross-references/) links. The benefit is that Hugo will validate broken page links (but [not references](https://github.com/gohugoio/hugo/issues/6863)).

I did some search and replace to test this out but before validating all data I wanted to see if such a patch would be accepted.

### Actual Behavior

```markdown
[default cache behavior (standard caching)](/cache/about/default-cache-behavior/)
```

### Expected Behavior

```markdown
[default cache behavior (standard caching)]({{< ref "/cache/about/default-cache-behavior" >}})
```

### Additional information

If you mess links up, Hugo will warn on compilation:
```
ERROR 2022/11/13 14:29:14 [en] REF_NOT_FOUND: Ref "/cache/about/cache-keysss": "/Users/jbergstroem/wrk/oss/cloudflare-docs/content/cache/best-practices/cache-performance.md:17:6": page not found

**Comment by KianNH** [comment]
Oooo, this is cool.

cc @kodster28 - I believe you're the last person who worked on the `bin/crawl.ts` stuff so thought you'd wanna see this.

**Comment by kodster28** [comment]
Thought about this quite a bit.

Agree this might be a more elegant approach, but don't think it fits the character of our contributor base.

Since this is a pretty open repo (and an open repo where we can't assume everyone knows Hugo syntax), I think we'd want to keep our current setup of markdown links with a GH check on the backend. Otherwise, think we'd get in the place of either having to constantly audit for `ref` instead of links or still keeping the `crawl` script anyways to catch traditional markdown links that get introduced.

Thanks for the suggestion and thought though @jbergstroem. Definitely worth the time I spent weighing this.
