### ISSUE TITLE
Add MARP presentation framework deployment instructions

### ISSUE THREAD

**Issue by pataquets** [cloudflare/cloudflare-docs#7579]
### Which Cloudflare product(s) does this pertain to?

Pages

### Subject Matter

Add MARP presentation framework deployment instructions

### Content Location

New document

### Additional information

The framework: https://marp.app/
I couldn't find how to add frameworks myself, especially given that supporting it would be a matter of simply running `npm run deck` and pushing the resulting `/public` directory.
Where are frameworks defined?

**Comment by GregBrimble** [comment]
Hi @pataquets! Thanks for your filing your interest in adding documentation for the Marp framework to Pages. Can you confirm where you found the instructions to run `npm run deck` and the setting `/public` as the build output directory?

As far as I can see, [this CLI](https://www.npmjs.com/package/@marp-team/marp-cli) is the officially supported way to building with Marp and I'm not seeing any reference to those settings.

In order to add a framework guide for Pages, we need a widely adopted standard for how projects are structured and built :)

**Comment by kodster28** [comment]
Howdy @pataquets, this has been sitting for a while.

Any answer to Greg's question above? If we don't have enough info to action, then we'll need to close this out.

**Comment by kodster28** [comment]
Closing this out due to a lack of information. If this is still an issue and I'm closing this out in error, feel free to re-open another issue (and tag me!).
