### ISSUE TITLE
Rule "Skip" doesn't skip Workers

### ISSUE THREAD

**Issue by wolruf** [cloudflare/cloudflare-docs#7593]
### Which Cloudflare product does this pertain to?

WAF

### Existing documentation URL(s)

https://developers.cloudflare.com/waf/custom-rules/skip/

### Section that requires update

A note or tip.

### What needs to change?

The documentation doesn't mention that "Skip" will always result in Workers running anyway (given there's a Workers Route of course)

### How should it change?

Add a tip or a note.

**Comment by sh471** [comment]
Web Application Firewall

**Comment by pedrosousa** [comment]
Hi @wolruf 
We say in the documentation that the skip action allows you to skip security features, and Workers is not a security feature. In the [skip options reference page](https://developers.cloudflare.com/waf/custom-rules/skip/options/), we specifically call out that skip rules do not skip Bot Fight Mode or Super Bot Fight Mode because those are in fact security features, so customers could wonder if these features would also be skipped.

Did we get questions from customers about Workers not being skipped with a skip rule?

**Comment by wolruf** [comment]
Yes, I had customers asking for it.
