### ISSUE TITLE
Cannot find "Account Home > Bulk Redirects"

### ISSUE THREAD

**Issue by praeclarum** [cloudflare/cloudflare-docs#9306]
### Which Cloudflare product does this pertain to?

Pages

### Existing documentation URL(s)

https://developers.cloudflare.com/pages/how-to/www-redirect/

### Section that requires update

Redirecting www to domain apex

### What needs to change?

I have looked all over my dashboard but cannot find this "Account Home > Bulk Redirects". This is what the navigation bar looks like:

<img width="255" alt="Screenshot 2023-06-09 at 6 36 49 AM" src="https://github.com/cloudflare/cloudflare-docs/assets/323548/329dd53f-7cb0-47f4-8f8d-c273207f2643">

### How should it change?

Please update the doc to say how to get to these "Bulk Redirects"

I cannot find "Account Home" either.

**Comment by crwaters16** [comment]
Hi @praeclarum 👋🏻  Looks like you're in the dashboard nav for a website rather than for your account. Select the Cloudflare icon in the top left of the Cloudflare dashboard and choose the account you're trying to follow the procedure for. Navigation should look like this:

![Cloudflare-account-navigation](https://github.com/cloudflare/cloudflare-docs/assets/78226508/e48798f1-604b-41b7-bdac-7413eca0775b)
